// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/supplier/types.proto

package com.yuanmai.protobuf.mall.supplier;

public interface SupplierInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mall.protobuf.supplier.SupplierInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 companyId = 2;</code>
   * @return The companyId.
   */
  int getCompanyId();

  /**
   * <code>int64 userId = 3;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.mall.protobuf.company.Company company = 5;</code>
   * @return Whether the company field is set.
   */
  boolean hasCompany();
  /**
   * <code>.mall.protobuf.company.Company company = 5;</code>
   * @return The company.
   */
  com.yuanmai.protobuf.mall.company.Company getCompany();
  /**
   * <code>.mall.protobuf.company.Company company = 5;</code>
   */
  com.yuanmai.protobuf.mall.company.CompanyOrBuilder getCompanyOrBuilder();

  /**
   * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
   * @return The status.
   */
  com.yuanmai.protobuf.mall.supplier.SupplierStatus getStatus();

  /**
   * <code>bool hasWarehouse = 7;</code>
   * @return The hasWarehouse.
   */
  boolean getHasWarehouse();

  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  java.util.List<com.yuanmai.protobuf.mall.supplier.WareConnect> 
      getWhConnectList();
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  com.yuanmai.protobuf.mall.supplier.WareConnect getWhConnect(int index);
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  int getWhConnectCount();
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  java.util.List<? extends com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder> 
      getWhConnectOrBuilderList();
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder getWhConnectOrBuilder(
      int index);
}
