// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/supplier/types.proto

package com.yuanmai.protobuf.mall.supplier;

/**
 * <pre>
 * 供货商信息
 * </pre>
 *
 * Protobuf type {@code mall.protobuf.supplier.SupplierInfo}
 */
public final class SupplierInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mall.protobuf.supplier.SupplierInfo)
    SupplierInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SupplierInfo.newBuilder() to construct.
  private SupplierInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SupplierInfo() {
    name_ = "";
    status_ = 0;
    whConnect_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SupplierInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.supplier.Types.internal_static_mall_protobuf_supplier_SupplierInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuanmai.protobuf.mall.supplier.Types.internal_static_mall_protobuf_supplier_SupplierInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuanmai.protobuf.mall.supplier.SupplierInfo.class, com.yuanmai.protobuf.mall.supplier.SupplierInfo.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int COMPANYID_FIELD_NUMBER = 2;
  private int companyId_ = 0;
  /**
   * <code>int32 companyId = 2;</code>
   * @return The companyId.
   */
  @java.lang.Override
  public int getCompanyId() {
    return companyId_;
  }

  public static final int USERID_FIELD_NUMBER = 3;
  private long userId_ = 0L;
  /**
   * <code>int64 userId = 3;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_FIELD_NUMBER = 5;
  private com.yuanmai.protobuf.mall.company.Company company_;
  /**
   * <code>.mall.protobuf.company.Company company = 5;</code>
   * @return Whether the company field is set.
   */
  @java.lang.Override
  public boolean hasCompany() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mall.protobuf.company.Company company = 5;</code>
   * @return The company.
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.company.Company getCompany() {
    return company_ == null ? com.yuanmai.protobuf.mall.company.Company.getDefaultInstance() : company_;
  }
  /**
   * <code>.mall.protobuf.company.Company company = 5;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.company.CompanyOrBuilder getCompanyOrBuilder() {
    return company_ == null ? com.yuanmai.protobuf.mall.company.Company.getDefaultInstance() : company_;
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_ = 0;
  /**
   * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
   * @return The status.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.supplier.SupplierStatus getStatus() {
    com.yuanmai.protobuf.mall.supplier.SupplierStatus result = com.yuanmai.protobuf.mall.supplier.SupplierStatus.forNumber(status_);
    return result == null ? com.yuanmai.protobuf.mall.supplier.SupplierStatus.UNRECOGNIZED : result;
  }

  public static final int HASWAREHOUSE_FIELD_NUMBER = 7;
  private boolean hasWarehouse_ = false;
  /**
   * <code>bool hasWarehouse = 7;</code>
   * @return The hasWarehouse.
   */
  @java.lang.Override
  public boolean getHasWarehouse() {
    return hasWarehouse_;
  }

  public static final int WHCONNECT_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<com.yuanmai.protobuf.mall.supplier.WareConnect> whConnect_;
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  @java.lang.Override
  public java.util.List<com.yuanmai.protobuf.mall.supplier.WareConnect> getWhConnectList() {
    return whConnect_;
  }
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder> 
      getWhConnectOrBuilderList() {
    return whConnect_;
  }
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  @java.lang.Override
  public int getWhConnectCount() {
    return whConnect_.size();
  }
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.supplier.WareConnect getWhConnect(int index) {
    return whConnect_.get(index);
  }
  /**
   * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder getWhConnectOrBuilder(
      int index) {
    return whConnect_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (companyId_ != 0) {
      output.writeInt32(2, companyId_);
    }
    if (userId_ != 0L) {
      output.writeInt64(3, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getCompany());
    }
    if (status_ != com.yuanmai.protobuf.mall.supplier.SupplierStatus.NORAML.getNumber()) {
      output.writeEnum(6, status_);
    }
    if (hasWarehouse_ != false) {
      output.writeBool(7, hasWarehouse_);
    }
    for (int i = 0; i < whConnect_.size(); i++) {
      output.writeMessage(8, whConnect_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (companyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, companyId_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCompany());
    }
    if (status_ != com.yuanmai.protobuf.mall.supplier.SupplierStatus.NORAML.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    if (hasWarehouse_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, hasWarehouse_);
    }
    for (int i = 0; i < whConnect_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, whConnect_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yuanmai.protobuf.mall.supplier.SupplierInfo)) {
      return super.equals(obj);
    }
    com.yuanmai.protobuf.mall.supplier.SupplierInfo other = (com.yuanmai.protobuf.mall.supplier.SupplierInfo) obj;

    if (getId()
        != other.getId()) return false;
    if (getCompanyId()
        != other.getCompanyId()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasCompany() != other.hasCompany()) return false;
    if (hasCompany()) {
      if (!getCompany()
          .equals(other.getCompany())) return false;
    }
    if (status_ != other.status_) return false;
    if (getHasWarehouse()
        != other.getHasWarehouse()) return false;
    if (!getWhConnectList()
        .equals(other.getWhConnectList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyId();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasCompany()) {
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + HASWAREHOUSE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasWarehouse());
    if (getWhConnectCount() > 0) {
      hash = (37 * hash) + WHCONNECT_FIELD_NUMBER;
      hash = (53 * hash) + getWhConnectList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yuanmai.protobuf.mall.supplier.SupplierInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 供货商信息
   * </pre>
   *
   * Protobuf type {@code mall.protobuf.supplier.SupplierInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mall.protobuf.supplier.SupplierInfo)
      com.yuanmai.protobuf.mall.supplier.SupplierInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuanmai.protobuf.mall.supplier.Types.internal_static_mall_protobuf_supplier_SupplierInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuanmai.protobuf.mall.supplier.Types.internal_static_mall_protobuf_supplier_SupplierInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuanmai.protobuf.mall.supplier.SupplierInfo.class, com.yuanmai.protobuf.mall.supplier.SupplierInfo.Builder.class);
    }

    // Construct using com.yuanmai.protobuf.mall.supplier.SupplierInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCompanyFieldBuilder();
        getWhConnectFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      companyId_ = 0;
      userId_ = 0L;
      name_ = "";
      company_ = null;
      if (companyBuilder_ != null) {
        companyBuilder_.dispose();
        companyBuilder_ = null;
      }
      status_ = 0;
      hasWarehouse_ = false;
      if (whConnectBuilder_ == null) {
        whConnect_ = java.util.Collections.emptyList();
      } else {
        whConnect_ = null;
        whConnectBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuanmai.protobuf.mall.supplier.Types.internal_static_mall_protobuf_supplier_SupplierInfo_descriptor;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.SupplierInfo getDefaultInstanceForType() {
      return com.yuanmai.protobuf.mall.supplier.SupplierInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.SupplierInfo build() {
      com.yuanmai.protobuf.mall.supplier.SupplierInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.SupplierInfo buildPartial() {
      com.yuanmai.protobuf.mall.supplier.SupplierInfo result = new com.yuanmai.protobuf.mall.supplier.SupplierInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yuanmai.protobuf.mall.supplier.SupplierInfo result) {
      if (whConnectBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          whConnect_ = java.util.Collections.unmodifiableList(whConnect_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.whConnect_ = whConnect_;
      } else {
        result.whConnect_ = whConnectBuilder_.build();
      }
    }

    private void buildPartial0(com.yuanmai.protobuf.mall.supplier.SupplierInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.companyId_ = companyId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.company_ = companyBuilder_ == null
            ? company_
            : companyBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.hasWarehouse_ = hasWarehouse_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuanmai.protobuf.mall.supplier.SupplierInfo) {
        return mergeFrom((com.yuanmai.protobuf.mall.supplier.SupplierInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuanmai.protobuf.mall.supplier.SupplierInfo other) {
      if (other == com.yuanmai.protobuf.mall.supplier.SupplierInfo.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getCompanyId() != 0) {
        setCompanyId(other.getCompanyId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasCompany()) {
        mergeCompany(other.getCompany());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getHasWarehouse() != false) {
        setHasWarehouse(other.getHasWarehouse());
      }
      if (whConnectBuilder_ == null) {
        if (!other.whConnect_.isEmpty()) {
          if (whConnect_.isEmpty()) {
            whConnect_ = other.whConnect_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureWhConnectIsMutable();
            whConnect_.addAll(other.whConnect_);
          }
          onChanged();
        }
      } else {
        if (!other.whConnect_.isEmpty()) {
          if (whConnectBuilder_.isEmpty()) {
            whConnectBuilder_.dispose();
            whConnectBuilder_ = null;
            whConnect_ = other.whConnect_;
            bitField0_ = (bitField0_ & ~0x00000080);
            whConnectBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWhConnectFieldBuilder() : null;
          } else {
            whConnectBuilder_.addAllMessages(other.whConnect_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              companyId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getCompanyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              hasWarehouse_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              com.yuanmai.protobuf.mall.supplier.WareConnect m =
                  input.readMessage(
                      com.yuanmai.protobuf.mall.supplier.WareConnect.parser(),
                      extensionRegistry);
              if (whConnectBuilder_ == null) {
                ensureWhConnectIsMutable();
                whConnect_.add(m);
              } else {
                whConnectBuilder_.addMessage(m);
              }
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int companyId_ ;
    /**
     * <code>int32 companyId = 2;</code>
     * @return The companyId.
     */
    @java.lang.Override
    public int getCompanyId() {
      return companyId_;
    }
    /**
     * <code>int32 companyId = 2;</code>
     * @param value The companyId to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyId(int value) {

      companyId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 companyId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      companyId_ = 0;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 3;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.yuanmai.protobuf.mall.company.Company company_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.yuanmai.protobuf.mall.company.Company, com.yuanmai.protobuf.mall.company.Company.Builder, com.yuanmai.protobuf.mall.company.CompanyOrBuilder> companyBuilder_;
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     * @return Whether the company field is set.
     */
    public boolean hasCompany() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     * @return The company.
     */
    public com.yuanmai.protobuf.mall.company.Company getCompany() {
      if (companyBuilder_ == null) {
        return company_ == null ? com.yuanmai.protobuf.mall.company.Company.getDefaultInstance() : company_;
      } else {
        return companyBuilder_.getMessage();
      }
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    public Builder setCompany(com.yuanmai.protobuf.mall.company.Company value) {
      if (companyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        company_ = value;
      } else {
        companyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    public Builder setCompany(
        com.yuanmai.protobuf.mall.company.Company.Builder builderForValue) {
      if (companyBuilder_ == null) {
        company_ = builderForValue.build();
      } else {
        companyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    public Builder mergeCompany(com.yuanmai.protobuf.mall.company.Company value) {
      if (companyBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          company_ != null &&
          company_ != com.yuanmai.protobuf.mall.company.Company.getDefaultInstance()) {
          getCompanyBuilder().mergeFrom(value);
        } else {
          company_ = value;
        }
      } else {
        companyBuilder_.mergeFrom(value);
      }
      if (company_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    public Builder clearCompany() {
      bitField0_ = (bitField0_ & ~0x00000010);
      company_ = null;
      if (companyBuilder_ != null) {
        companyBuilder_.dispose();
        companyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    public com.yuanmai.protobuf.mall.company.Company.Builder getCompanyBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getCompanyFieldBuilder().getBuilder();
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    public com.yuanmai.protobuf.mall.company.CompanyOrBuilder getCompanyOrBuilder() {
      if (companyBuilder_ != null) {
        return companyBuilder_.getMessageOrBuilder();
      } else {
        return company_ == null ?
            com.yuanmai.protobuf.mall.company.Company.getDefaultInstance() : company_;
      }
    }
    /**
     * <code>.mall.protobuf.company.Company company = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.yuanmai.protobuf.mall.company.Company, com.yuanmai.protobuf.mall.company.Company.Builder, com.yuanmai.protobuf.mall.company.CompanyOrBuilder> 
        getCompanyFieldBuilder() {
      if (companyBuilder_ == null) {
        companyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.yuanmai.protobuf.mall.company.Company, com.yuanmai.protobuf.mall.company.Company.Builder, com.yuanmai.protobuf.mall.company.CompanyOrBuilder>(
                getCompany(),
                getParentForChildren(),
                isClean());
        company_ = null;
      }
      return companyBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.SupplierStatus getStatus() {
      com.yuanmai.protobuf.mall.supplier.SupplierStatus result = com.yuanmai.protobuf.mall.supplier.SupplierStatus.forNumber(status_);
      return result == null ? com.yuanmai.protobuf.mall.supplier.SupplierStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.yuanmai.protobuf.mall.supplier.SupplierStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.supplier.SupplierStatus status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000020);
      status_ = 0;
      onChanged();
      return this;
    }

    private boolean hasWarehouse_ ;
    /**
     * <code>bool hasWarehouse = 7;</code>
     * @return The hasWarehouse.
     */
    @java.lang.Override
    public boolean getHasWarehouse() {
      return hasWarehouse_;
    }
    /**
     * <code>bool hasWarehouse = 7;</code>
     * @param value The hasWarehouse to set.
     * @return This builder for chaining.
     */
    public Builder setHasWarehouse(boolean value) {

      hasWarehouse_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasWarehouse = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasWarehouse() {
      bitField0_ = (bitField0_ & ~0x00000040);
      hasWarehouse_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.yuanmai.protobuf.mall.supplier.WareConnect> whConnect_ =
      java.util.Collections.emptyList();
    private void ensureWhConnectIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        whConnect_ = new java.util.ArrayList<com.yuanmai.protobuf.mall.supplier.WareConnect>(whConnect_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.supplier.WareConnect, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder, com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder> whConnectBuilder_;

    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.supplier.WareConnect> getWhConnectList() {
      if (whConnectBuilder_ == null) {
        return java.util.Collections.unmodifiableList(whConnect_);
      } else {
        return whConnectBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public int getWhConnectCount() {
      if (whConnectBuilder_ == null) {
        return whConnect_.size();
      } else {
        return whConnectBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public com.yuanmai.protobuf.mall.supplier.WareConnect getWhConnect(int index) {
      if (whConnectBuilder_ == null) {
        return whConnect_.get(index);
      } else {
        return whConnectBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder setWhConnect(
        int index, com.yuanmai.protobuf.mall.supplier.WareConnect value) {
      if (whConnectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWhConnectIsMutable();
        whConnect_.set(index, value);
        onChanged();
      } else {
        whConnectBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder setWhConnect(
        int index, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder builderForValue) {
      if (whConnectBuilder_ == null) {
        ensureWhConnectIsMutable();
        whConnect_.set(index, builderForValue.build());
        onChanged();
      } else {
        whConnectBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder addWhConnect(com.yuanmai.protobuf.mall.supplier.WareConnect value) {
      if (whConnectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWhConnectIsMutable();
        whConnect_.add(value);
        onChanged();
      } else {
        whConnectBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder addWhConnect(
        int index, com.yuanmai.protobuf.mall.supplier.WareConnect value) {
      if (whConnectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWhConnectIsMutable();
        whConnect_.add(index, value);
        onChanged();
      } else {
        whConnectBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder addWhConnect(
        com.yuanmai.protobuf.mall.supplier.WareConnect.Builder builderForValue) {
      if (whConnectBuilder_ == null) {
        ensureWhConnectIsMutable();
        whConnect_.add(builderForValue.build());
        onChanged();
      } else {
        whConnectBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder addWhConnect(
        int index, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder builderForValue) {
      if (whConnectBuilder_ == null) {
        ensureWhConnectIsMutable();
        whConnect_.add(index, builderForValue.build());
        onChanged();
      } else {
        whConnectBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder addAllWhConnect(
        java.lang.Iterable<? extends com.yuanmai.protobuf.mall.supplier.WareConnect> values) {
      if (whConnectBuilder_ == null) {
        ensureWhConnectIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, whConnect_);
        onChanged();
      } else {
        whConnectBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder clearWhConnect() {
      if (whConnectBuilder_ == null) {
        whConnect_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        whConnectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public Builder removeWhConnect(int index) {
      if (whConnectBuilder_ == null) {
        ensureWhConnectIsMutable();
        whConnect_.remove(index);
        onChanged();
      } else {
        whConnectBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public com.yuanmai.protobuf.mall.supplier.WareConnect.Builder getWhConnectBuilder(
        int index) {
      return getWhConnectFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder getWhConnectOrBuilder(
        int index) {
      if (whConnectBuilder_ == null) {
        return whConnect_.get(index);  } else {
        return whConnectBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public java.util.List<? extends com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder> 
         getWhConnectOrBuilderList() {
      if (whConnectBuilder_ != null) {
        return whConnectBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(whConnect_);
      }
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public com.yuanmai.protobuf.mall.supplier.WareConnect.Builder addWhConnectBuilder() {
      return getWhConnectFieldBuilder().addBuilder(
          com.yuanmai.protobuf.mall.supplier.WareConnect.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public com.yuanmai.protobuf.mall.supplier.WareConnect.Builder addWhConnectBuilder(
        int index) {
      return getWhConnectFieldBuilder().addBuilder(
          index, com.yuanmai.protobuf.mall.supplier.WareConnect.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.supplier.WareConnect whConnect = 8;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.supplier.WareConnect.Builder> 
         getWhConnectBuilderList() {
      return getWhConnectFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.supplier.WareConnect, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder, com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder> 
        getWhConnectFieldBuilder() {
      if (whConnectBuilder_ == null) {
        whConnectBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yuanmai.protobuf.mall.supplier.WareConnect, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder, com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder>(
                whConnect_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        whConnect_ = null;
      }
      return whConnectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mall.protobuf.supplier.SupplierInfo)
  }

  // @@protoc_insertion_point(class_scope:mall.protobuf.supplier.SupplierInfo)
  private static final com.yuanmai.protobuf.mall.supplier.SupplierInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yuanmai.protobuf.mall.supplier.SupplierInfo();
  }

  public static com.yuanmai.protobuf.mall.supplier.SupplierInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SupplierInfo>
      PARSER = new com.google.protobuf.AbstractParser<SupplierInfo>() {
    @java.lang.Override
    public SupplierInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SupplierInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SupplierInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yuanmai.protobuf.mall.supplier.SupplierInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

