// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/supplier/warehouse.proto

package com.yuanmai.protobuf.mall.supplier;

/**
 * Protobuf type {@code mall.protobuf.supplier.WareConnect}
 */
public final class WareConnect extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mall.protobuf.supplier.WareConnect)
    WareConnectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WareConnect.newBuilder() to construct.
  private WareConnect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WareConnect() {
    type_ = 0;
    mark_ = "";
    oauthCode_ = "";
    key_ = "";
    credential_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WareConnect();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.supplier.Warehouse.internal_static_mall_protobuf_supplier_WareConnect_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuanmai.protobuf.mall.supplier.Warehouse.internal_static_mall_protobuf_supplier_WareConnect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuanmai.protobuf.mall.supplier.WareConnect.class, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.supplier.WHConnectType getType() {
    com.yuanmai.protobuf.mall.supplier.WHConnectType result = com.yuanmai.protobuf.mall.supplier.WHConnectType.forNumber(type_);
    return result == null ? com.yuanmai.protobuf.mall.supplier.WHConnectType.UNRECOGNIZED : result;
  }

  public static final int MARK_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mark_ = "";
  /**
   * <code>string mark = 3;</code>
   * @return The mark.
   */
  @java.lang.Override
  public java.lang.String getMark() {
    java.lang.Object ref = mark_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mark_ = s;
      return s;
    }
  }
  /**
   * <code>string mark = 3;</code>
   * @return The bytes for mark.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMarkBytes() {
    java.lang.Object ref = mark_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OAUTHCODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object oauthCode_ = "";
  /**
   * <code>string oauthCode = 4;</code>
   * @return The oauthCode.
   */
  @java.lang.Override
  public java.lang.String getOauthCode() {
    java.lang.Object ref = oauthCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oauthCode_ = s;
      return s;
    }
  }
  /**
   * <code>string oauthCode = 4;</code>
   * @return The bytes for oauthCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOauthCodeBytes() {
    java.lang.Object ref = oauthCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oauthCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <code>string key = 5;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 5;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDENTIAL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object credential_ = "";
  /**
   * <code>string credential = 6;</code>
   * @return The credential.
   */
  @java.lang.Override
  public java.lang.String getCredential() {
    java.lang.Object ref = credential_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      credential_ = s;
      return s;
    }
  }
  /**
   * <code>string credential = 6;</code>
   * @return The bytes for credential.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCredentialBytes() {
    java.lang.Object ref = credential_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      credential_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 7;
  private com.google.type.DateTime time_;
  /**
   * <code>.google.type.DateTime time = 7;</code>
   * @return Whether the time field is set.
   */
  @java.lang.Override
  public boolean hasTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.type.DateTime time = 7;</code>
   * @return The time.
   */
  @java.lang.Override
  public com.google.type.DateTime getTime() {
    return time_ == null ? com.google.type.DateTime.getDefaultInstance() : time_;
  }
  /**
   * <code>.google.type.DateTime time = 7;</code>
   */
  @java.lang.Override
  public com.google.type.DateTimeOrBuilder getTimeOrBuilder() {
    return time_ == null ? com.google.type.DateTime.getDefaultInstance() : time_;
  }

  public static final int DEF_FIELD_NUMBER = 8;
  private boolean def_ = false;
  /**
   * <code>bool def = 8;</code>
   * @return The def.
   */
  @java.lang.Override
  public boolean getDef() {
    return def_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (type_ != com.yuanmai.protobuf.mall.supplier.WHConnectType.NONE.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mark_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mark_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oauthCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, oauthCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, key_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(credential_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, credential_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getTime());
    }
    if (def_ != false) {
      output.writeBool(8, def_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (type_ != com.yuanmai.protobuf.mall.supplier.WHConnectType.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mark_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mark_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oauthCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, oauthCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, key_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(credential_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, credential_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTime());
    }
    if (def_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, def_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yuanmai.protobuf.mall.supplier.WareConnect)) {
      return super.equals(obj);
    }
    com.yuanmai.protobuf.mall.supplier.WareConnect other = (com.yuanmai.protobuf.mall.supplier.WareConnect) obj;

    if (getId()
        != other.getId()) return false;
    if (type_ != other.type_) return false;
    if (!getMark()
        .equals(other.getMark())) return false;
    if (!getOauthCode()
        .equals(other.getOauthCode())) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getCredential()
        .equals(other.getCredential())) return false;
    if (hasTime() != other.hasTime()) return false;
    if (hasTime()) {
      if (!getTime()
          .equals(other.getTime())) return false;
    }
    if (getDef()
        != other.getDef()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + MARK_FIELD_NUMBER;
    hash = (53 * hash) + getMark().hashCode();
    hash = (37 * hash) + OAUTHCODE_FIELD_NUMBER;
    hash = (53 * hash) + getOauthCode().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + CREDENTIAL_FIELD_NUMBER;
    hash = (53 * hash) + getCredential().hashCode();
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (37 * hash) + DEF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDef());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.supplier.WareConnect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yuanmai.protobuf.mall.supplier.WareConnect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mall.protobuf.supplier.WareConnect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mall.protobuf.supplier.WareConnect)
      com.yuanmai.protobuf.mall.supplier.WareConnectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuanmai.protobuf.mall.supplier.Warehouse.internal_static_mall_protobuf_supplier_WareConnect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuanmai.protobuf.mall.supplier.Warehouse.internal_static_mall_protobuf_supplier_WareConnect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuanmai.protobuf.mall.supplier.WareConnect.class, com.yuanmai.protobuf.mall.supplier.WareConnect.Builder.class);
    }

    // Construct using com.yuanmai.protobuf.mall.supplier.WareConnect.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      type_ = 0;
      mark_ = "";
      oauthCode_ = "";
      key_ = "";
      credential_ = "";
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      def_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuanmai.protobuf.mall.supplier.Warehouse.internal_static_mall_protobuf_supplier_WareConnect_descriptor;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.WareConnect getDefaultInstanceForType() {
      return com.yuanmai.protobuf.mall.supplier.WareConnect.getDefaultInstance();
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.WareConnect build() {
      com.yuanmai.protobuf.mall.supplier.WareConnect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.WareConnect buildPartial() {
      com.yuanmai.protobuf.mall.supplier.WareConnect result = new com.yuanmai.protobuf.mall.supplier.WareConnect(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yuanmai.protobuf.mall.supplier.WareConnect result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mark_ = mark_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.oauthCode_ = oauthCode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.key_ = key_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.credential_ = credential_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.time_ = timeBuilder_ == null
            ? time_
            : timeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.def_ = def_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuanmai.protobuf.mall.supplier.WareConnect) {
        return mergeFrom((com.yuanmai.protobuf.mall.supplier.WareConnect)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuanmai.protobuf.mall.supplier.WareConnect other) {
      if (other == com.yuanmai.protobuf.mall.supplier.WareConnect.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getMark().isEmpty()) {
        mark_ = other.mark_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getOauthCode().isEmpty()) {
        oauthCode_ = other.oauthCode_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getCredential().isEmpty()) {
        credential_ = other.credential_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (other.getDef() != false) {
        setDef(other.getDef());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              mark_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              oauthCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              credential_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              def_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.supplier.WHConnectType getType() {
      com.yuanmai.protobuf.mall.supplier.WHConnectType result = com.yuanmai.protobuf.mall.supplier.WHConnectType.forNumber(type_);
      return result == null ? com.yuanmai.protobuf.mall.supplier.WHConnectType.UNRECOGNIZED : result;
    }
    /**
     * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.yuanmai.protobuf.mall.supplier.WHConnectType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.supplier.WHConnectType type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mark_ = "";
    /**
     * <code>string mark = 3;</code>
     * @return The mark.
     */
    public java.lang.String getMark() {
      java.lang.Object ref = mark_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mark_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mark = 3;</code>
     * @return The bytes for mark.
     */
    public com.google.protobuf.ByteString
        getMarkBytes() {
      java.lang.Object ref = mark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mark = 3;</code>
     * @param value The mark to set.
     * @return This builder for chaining.
     */
    public Builder setMark(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mark_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string mark = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMark() {
      mark_ = getDefaultInstance().getMark();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string mark = 3;</code>
     * @param value The bytes for mark to set.
     * @return This builder for chaining.
     */
    public Builder setMarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mark_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object oauthCode_ = "";
    /**
     * <code>string oauthCode = 4;</code>
     * @return The oauthCode.
     */
    public java.lang.String getOauthCode() {
      java.lang.Object ref = oauthCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oauthCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oauthCode = 4;</code>
     * @return The bytes for oauthCode.
     */
    public com.google.protobuf.ByteString
        getOauthCodeBytes() {
      java.lang.Object ref = oauthCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oauthCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oauthCode = 4;</code>
     * @param value The oauthCode to set.
     * @return This builder for chaining.
     */
    public Builder setOauthCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      oauthCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string oauthCode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOauthCode() {
      oauthCode_ = getDefaultInstance().getOauthCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string oauthCode = 4;</code>
     * @param value The bytes for oauthCode to set.
     * @return This builder for chaining.
     */
    public Builder setOauthCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      oauthCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 5;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 5;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 5;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string key = 5;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object credential_ = "";
    /**
     * <code>string credential = 6;</code>
     * @return The credential.
     */
    public java.lang.String getCredential() {
      java.lang.Object ref = credential_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        credential_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string credential = 6;</code>
     * @return The bytes for credential.
     */
    public com.google.protobuf.ByteString
        getCredentialBytes() {
      java.lang.Object ref = credential_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        credential_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string credential = 6;</code>
     * @param value The credential to set.
     * @return This builder for chaining.
     */
    public Builder setCredential(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      credential_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string credential = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredential() {
      credential_ = getDefaultInstance().getCredential();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string credential = 6;</code>
     * @param value The bytes for credential to set.
     * @return This builder for chaining.
     */
    public Builder setCredentialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      credential_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.type.DateTime time_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder> timeBuilder_;
    /**
     * <code>.google.type.DateTime time = 7;</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     * @return The time.
     */
    public com.google.type.DateTime getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.google.type.DateTime.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    public Builder setTime(com.google.type.DateTime value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
      } else {
        timeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    public Builder setTime(
        com.google.type.DateTime.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    public Builder mergeTime(com.google.type.DateTime value) {
      if (timeBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          time_ != null &&
          time_ != com.google.type.DateTime.getDefaultInstance()) {
          getTimeBuilder().mergeFrom(value);
        } else {
          time_ = value;
        }
      } else {
        timeBuilder_.mergeFrom(value);
      }
      if (time_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    public com.google.type.DateTime.Builder getTimeBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    public com.google.type.DateTimeOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.google.type.DateTime.getDefaultInstance() : time_;
      }
    }
    /**
     * <code>.google.type.DateTime time = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.DateTime, com.google.type.DateTime.Builder, com.google.type.DateTimeOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private boolean def_ ;
    /**
     * <code>bool def = 8;</code>
     * @return The def.
     */
    @java.lang.Override
    public boolean getDef() {
      return def_;
    }
    /**
     * <code>bool def = 8;</code>
     * @param value The def to set.
     * @return This builder for chaining.
     */
    public Builder setDef(boolean value) {

      def_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool def = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDef() {
      bitField0_ = (bitField0_ & ~0x00000080);
      def_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mall.protobuf.supplier.WareConnect)
  }

  // @@protoc_insertion_point(class_scope:mall.protobuf.supplier.WareConnect)
  private static final com.yuanmai.protobuf.mall.supplier.WareConnect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yuanmai.protobuf.mall.supplier.WareConnect();
  }

  public static com.yuanmai.protobuf.mall.supplier.WareConnect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WareConnect>
      PARSER = new com.google.protobuf.AbstractParser<WareConnect>() {
    @java.lang.Override
    public WareConnect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WareConnect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WareConnect> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yuanmai.protobuf.mall.supplier.WareConnect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

