// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/express/types.proto

package com.yuanmai.protobuf.mall.express;

public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mall.protobuf.express.Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time = 1;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string time = 1;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string context = 2;</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>string context = 2;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>string remark = 3;</code>
   * @return The remark.
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 3;</code>
   * @return The bytes for remark.
   */
  com.google.protobuf.ByteString
      getRemarkBytes();

  /**
   * <code>string address = 4;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 code = 5;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string location = 6;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 6;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string action = 7;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 7;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
