// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/pay/types.proto

package com.yuanmai.protobuf.mall.pay;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035mall/protobuf/pay/types.proto\022\021mall.pr" +
      "otobuf.pay\032\031google/protobuf/any.proto\032\032g" +
      "oogle/type/datetime.protoBQ\n\035com.yuanmai" +
      ".protobuf.mall.payP\001Z.github.com/buzzxu/" +
      "yuanmai-mall-protobuf-go;payb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.type.DateTimeProto.getDescriptor(),
        });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.type.DateTimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
