// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/settle/types.proto

package com.yuanmai.protobuf.mall.settle;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n mall/protobuf/settle/types.proto\022\024mall" +
      ".protobuf.settle*\223\001\n\020SettlementMethod\022\010\n" +
      "\004NONE\020\000\022\014\n\010DELIVERY\020\001\022\007\n\003DAY\020\002\022\010\n\004WEEK\020\003" +
      "\022\t\n\005MONTH\020\004\022\016\n\nCURR_MONTH\020\005\022\013\n\007DAYS_60\020\006" +
      "\022\013\n\007DAYS_90\020\007\022\n\n\006SEASON\020\010\022\n\n\006DAYS_3\020\t\022\007\n" +
      "\003MIX\020c*?\n\020SettlementStatus\022\017\n\013STATUS_NON" +
      "E\020\000\022\r\n\tSUBMITTED\020\001\022\013\n\007SUCCESS\020\002BW\n com.y" +
      "uanmai.protobuf.mall.settleP\001Z1github.co" +
      "m/buzzxu/yuanmai-mall-protobuf-go;settle" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
