// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/order/types.proto

package com.yuanmai.protobuf.mall.order;

public interface ItemSpecValOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mall.protobuf.order.ItemSpecVal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.google.protobuf.Any value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.google.protobuf.Any value = 3;</code>
   * @return The value.
   */
  com.google.protobuf.Any getValue();
  /**
   * <code>.google.protobuf.Any value = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getValueOrBuilder();
}
