// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/order/order.proto

package com.yuanmai.protobuf.mall.order;

public interface OrderInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mall.protobuf.order.OrderInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string parentOrderNumber = 3;</code>
   * @return The parentOrderNumber.
   */
  java.lang.String getParentOrderNumber();
  /**
   * <code>string parentOrderNumber = 3;</code>
   * @return The bytes for parentOrderNumber.
   */
  com.google.protobuf.ByteString
      getParentOrderNumberBytes();

  /**
   * <code>string orderNumber = 4;</code>
   * @return The orderNumber.
   */
  java.lang.String getOrderNumber();
  /**
   * <code>string orderNumber = 4;</code>
   * @return The bytes for orderNumber.
   */
  com.google.protobuf.ByteString
      getOrderNumberBytes();

  /**
   * <code>.mall.protobuf.order.OrderState state = 5;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.mall.protobuf.order.OrderState state = 5;</code>
   * @return The state.
   */
  com.yuanmai.protobuf.mall.order.OrderState getState();

  /**
   * <code>.yuanmai.protobuf.pay.PayState payState = 6;</code>
   * @return The enum numeric value on the wire for payState.
   */
  int getPayStateValue();
  /**
   * <code>.yuanmai.protobuf.pay.PayState payState = 6;</code>
   * @return The payState.
   */
  com.yuanmai.protobuf.pay.PayState getPayState();

  /**
   * <code>.yuanmai.protobuf.pay.RefundState refundState = 7;</code>
   * @return The enum numeric value on the wire for refundState.
   */
  int getRefundStateValue();
  /**
   * <code>.yuanmai.protobuf.pay.RefundState refundState = 7;</code>
   * @return The refundState.
   */
  com.yuanmai.protobuf.pay.RefundState getRefundState();

  /**
   * <code>.mall.protobuf.aftersale.AfterState afterState = 8;</code>
   * @return The enum numeric value on the wire for afterState.
   */
  int getAfterStateValue();
  /**
   * <code>.mall.protobuf.aftersale.AfterState afterState = 8;</code>
   * @return The afterState.
   */
  com.yuanmai.protobuf.mall.aftersale.AfterState getAfterState();

  /**
   * <code>int32 supplierId = 9;</code>
   * @return The supplierId.
   */
  int getSupplierId();

  /**
   * <code>int32 number = 10;</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <code>int32 shippedNumber = 11;</code>
   * @return The shippedNumber.
   */
  int getShippedNumber();

  /**
   * <code>int64 totalAmount = 12;</code>
   * @return The totalAmount.
   */
  long getTotalAmount();

  /**
   * <code>int64 totalAmountCost = 13;</code>
   * @return The totalAmountCost.
   */
  long getTotalAmountCost();

  /**
   * <code>int64 fee = 14;</code>
   * @return The fee.
   */
  long getFee();

  /**
   * <code>int64 payTotalAmount = 15;</code>
   * @return The payTotalAmount.
   */
  long getPayTotalAmount();

  /**
   * <code>int64 freeAmount = 16;</code>
   * @return The freeAmount.
   */
  long getFreeAmount();

  /**
   * <code>int64 settlAmount = 17;</code>
   * @return The settlAmount.
   */
  long getSettlAmount();

  /**
   * <code>int64 logisticsFee = 18;</code>
   * @return The logisticsFee.
   */
  long getLogisticsFee();

  /**
   * <code>int64 discount = 19;</code>
   * @return The discount.
   */
  long getDiscount();

  /**
   * <code>int64 refundAmount = 20;</code>
   * @return The refundAmount.
   */
  long getRefundAmount();

  /**
   * <code>int32 integral = 21;</code>
   * @return The integral.
   */
  int getIntegral();

  /**
   * <code>int64 addressId = 22;</code>
   * @return The addressId.
   */
  long getAddressId();

  /**
   * <code>string consignee = 23;</code>
   * @return The consignee.
   */
  java.lang.String getConsignee();
  /**
   * <code>string consignee = 23;</code>
   * @return The bytes for consignee.
   */
  com.google.protobuf.ByteString
      getConsigneeBytes();

  /**
   * <code>string phone = 24;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 24;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string address = 25;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 25;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>.yuanmai.protobuf.pay.PayChannel payChannel = 26;</code>
   * @return The enum numeric value on the wire for payChannel.
   */
  int getPayChannelValue();
  /**
   * <code>.yuanmai.protobuf.pay.PayChannel payChannel = 26;</code>
   * @return The payChannel.
   */
  com.yuanmai.protobuf.pay.PayChannel getPayChannel();

  /**
   * <code>string tradeNo = 27;</code>
   * @return The tradeNo.
   */
  java.lang.String getTradeNo();
  /**
   * <code>string tradeNo = 27;</code>
   * @return The bytes for tradeNo.
   */
  com.google.protobuf.ByteString
      getTradeNoBytes();

  /**
   * <code>string outTradeNo = 28;</code>
   * @return The outTradeNo.
   */
  java.lang.String getOutTradeNo();
  /**
   * <code>string outTradeNo = 28;</code>
   * @return The bytes for outTradeNo.
   */
  com.google.protobuf.ByteString
      getOutTradeNoBytes();

  /**
   * <code>string refundNo = 29;</code>
   * @return The refundNo.
   */
  java.lang.String getRefundNo();
  /**
   * <code>string refundNo = 29;</code>
   * @return The bytes for refundNo.
   */
  com.google.protobuf.ByteString
      getRefundNoBytes();

  /**
   * <code>string outRefundNo = 30;</code>
   * @return The outRefundNo.
   */
  java.lang.String getOutRefundNo();
  /**
   * <code>string outRefundNo = 30;</code>
   * @return The bytes for outRefundNo.
   */
  com.google.protobuf.ByteString
      getOutRefundNoBytes();

  /**
   * <code>.mall.protobuf.settle.SettlementStatus settlementState = 31;</code>
   * @return The enum numeric value on the wire for settlementState.
   */
  int getSettlementStateValue();
  /**
   * <code>.mall.protobuf.settle.SettlementStatus settlementState = 31;</code>
   * @return The settlementState.
   */
  com.yuanmai.protobuf.mall.settle.SettlementStatus getSettlementState();

  /**
   * <code>.google.type.DateTime settlementTime = 32;</code>
   * @return Whether the settlementTime field is set.
   */
  boolean hasSettlementTime();
  /**
   * <code>.google.type.DateTime settlementTime = 32;</code>
   * @return The settlementTime.
   */
  com.google.type.DateTime getSettlementTime();
  /**
   * <code>.google.type.DateTime settlementTime = 32;</code>
   */
  com.google.type.DateTimeOrBuilder getSettlementTimeOrBuilder();

  /**
   * <code>string remark = 33;</code>
   * @return The remark.
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 33;</code>
   * @return The bytes for remark.
   */
  com.google.protobuf.ByteString
      getRemarkBytes();

  /**
   * <code>string reason = 34;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 34;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>.google.type.DateTime submitPayTime = 35;</code>
   * @return Whether the submitPayTime field is set.
   */
  boolean hasSubmitPayTime();
  /**
   * <code>.google.type.DateTime submitPayTime = 35;</code>
   * @return The submitPayTime.
   */
  com.google.type.DateTime getSubmitPayTime();
  /**
   * <code>.google.type.DateTime submitPayTime = 35;</code>
   */
  com.google.type.DateTimeOrBuilder getSubmitPayTimeOrBuilder();

  /**
   * <code>.google.type.DateTime submitRefundTime = 36;</code>
   * @return Whether the submitRefundTime field is set.
   */
  boolean hasSubmitRefundTime();
  /**
   * <code>.google.type.DateTime submitRefundTime = 36;</code>
   * @return The submitRefundTime.
   */
  com.google.type.DateTime getSubmitRefundTime();
  /**
   * <code>.google.type.DateTime submitRefundTime = 36;</code>
   */
  com.google.type.DateTimeOrBuilder getSubmitRefundTimeOrBuilder();

  /**
   * <code>.google.type.DateTime payTime = 37;</code>
   * @return Whether the payTime field is set.
   */
  boolean hasPayTime();
  /**
   * <code>.google.type.DateTime payTime = 37;</code>
   * @return The payTime.
   */
  com.google.type.DateTime getPayTime();
  /**
   * <code>.google.type.DateTime payTime = 37;</code>
   */
  com.google.type.DateTimeOrBuilder getPayTimeOrBuilder();

  /**
   * <code>.google.type.DateTime refundTime = 38;</code>
   * @return Whether the refundTime field is set.
   */
  boolean hasRefundTime();
  /**
   * <code>.google.type.DateTime refundTime = 38;</code>
   * @return The refundTime.
   */
  com.google.type.DateTime getRefundTime();
  /**
   * <code>.google.type.DateTime refundTime = 38;</code>
   */
  com.google.type.DateTimeOrBuilder getRefundTimeOrBuilder();

  /**
   * <code>.google.type.DateTime deliveryTime = 39;</code>
   * @return Whether the deliveryTime field is set.
   */
  boolean hasDeliveryTime();
  /**
   * <code>.google.type.DateTime deliveryTime = 39;</code>
   * @return The deliveryTime.
   */
  com.google.type.DateTime getDeliveryTime();
  /**
   * <code>.google.type.DateTime deliveryTime = 39;</code>
   */
  com.google.type.DateTimeOrBuilder getDeliveryTimeOrBuilder();

  /**
   * <code>.google.type.DateTime signedTIme = 40;</code>
   * @return Whether the signedTIme field is set.
   */
  boolean hasSignedTIme();
  /**
   * <code>.google.type.DateTime signedTIme = 40;</code>
   * @return The signedTIme.
   */
  com.google.type.DateTime getSignedTIme();
  /**
   * <code>.google.type.DateTime signedTIme = 40;</code>
   */
  com.google.type.DateTimeOrBuilder getSignedTImeOrBuilder();

  /**
   * <code>.google.type.DateTime afterFinishTime = 41;</code>
   * @return Whether the afterFinishTime field is set.
   */
  boolean hasAfterFinishTime();
  /**
   * <code>.google.type.DateTime afterFinishTime = 41;</code>
   * @return The afterFinishTime.
   */
  com.google.type.DateTime getAfterFinishTime();
  /**
   * <code>.google.type.DateTime afterFinishTime = 41;</code>
   */
  com.google.type.DateTimeOrBuilder getAfterFinishTimeOrBuilder();

  /**
   * <code>.google.type.DateTime endTime = 42;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>.google.type.DateTime endTime = 42;</code>
   * @return The endTime.
   */
  com.google.type.DateTime getEndTime();
  /**
   * <code>.google.type.DateTime endTime = 42;</code>
   */
  com.google.type.DateTimeOrBuilder getEndTimeOrBuilder();

  /**
   * <code>repeated .mall.protobuf.order.OrderItem items = 43;</code>
   */
  java.util.List<com.yuanmai.protobuf.mall.order.OrderItem> 
      getItemsList();
  /**
   * <code>repeated .mall.protobuf.order.OrderItem items = 43;</code>
   */
  com.yuanmai.protobuf.mall.order.OrderItem getItems(int index);
  /**
   * <code>repeated .mall.protobuf.order.OrderItem items = 43;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .mall.protobuf.order.OrderItem items = 43;</code>
   */
  java.util.List<? extends com.yuanmai.protobuf.mall.order.OrderItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .mall.protobuf.order.OrderItem items = 43;</code>
   */
  com.yuanmai.protobuf.mall.order.OrderItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>repeated .mall.protobuf.order.OrderDelivery deliveries = 44;</code>
   */
  java.util.List<com.yuanmai.protobuf.mall.order.OrderDelivery> 
      getDeliveriesList();
  /**
   * <code>repeated .mall.protobuf.order.OrderDelivery deliveries = 44;</code>
   */
  com.yuanmai.protobuf.mall.order.OrderDelivery getDeliveries(int index);
  /**
   * <code>repeated .mall.protobuf.order.OrderDelivery deliveries = 44;</code>
   */
  int getDeliveriesCount();
  /**
   * <code>repeated .mall.protobuf.order.OrderDelivery deliveries = 44;</code>
   */
  java.util.List<? extends com.yuanmai.protobuf.mall.order.OrderDeliveryOrBuilder> 
      getDeliveriesOrBuilderList();
  /**
   * <code>repeated .mall.protobuf.order.OrderDelivery deliveries = 44;</code>
   */
  com.yuanmai.protobuf.mall.order.OrderDeliveryOrBuilder getDeliveriesOrBuilder(
      int index);

  /**
   * <code>.mall.protobuf.aftersale.AfterSaleOrderInfo afterSaleOrder = 45;</code>
   * @return Whether the afterSaleOrder field is set.
   */
  boolean hasAfterSaleOrder();
  /**
   * <code>.mall.protobuf.aftersale.AfterSaleOrderInfo afterSaleOrder = 45;</code>
   * @return The afterSaleOrder.
   */
  com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo getAfterSaleOrder();
  /**
   * <code>.mall.protobuf.aftersale.AfterSaleOrderInfo afterSaleOrder = 45;</code>
   */
  com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfoOrBuilder getAfterSaleOrderOrBuilder();

  /**
   * <code>.yuanmai.protobuf.pay.PaymentMethod paymentMethod = 46;</code>
   * @return The enum numeric value on the wire for paymentMethod.
   */
  int getPaymentMethodValue();
  /**
   * <code>.yuanmai.protobuf.pay.PaymentMethod paymentMethod = 46;</code>
   * @return The paymentMethod.
   */
  com.yuanmai.protobuf.pay.PaymentMethod getPaymentMethod();

  /**
   * <code>.mall.protobuf.settle.SettlementMethod settlMethod = 47;</code>
   * @return The enum numeric value on the wire for settlMethod.
   */
  int getSettlMethodValue();
  /**
   * <code>.mall.protobuf.settle.SettlementMethod settlMethod = 47;</code>
   * @return The settlMethod.
   */
  com.yuanmai.protobuf.mall.settle.SettlementMethod getSettlMethod();

  /**
   * <code>int64 payerId = 48;</code>
   * @return The payerId.
   */
  long getPayerId();

  /**
   * <code>string payer = 49;</code>
   * @return The payer.
   */
  java.lang.String getPayer();
  /**
   * <code>string payer = 49;</code>
   * @return The bytes for payer.
   */
  com.google.protobuf.ByteString
      getPayerBytes();

  /**
   * <code>bool fapiao = 50;</code>
   * @return The fapiao.
   */
  boolean getFapiao();

  /**
   * <code>int64 billId = 51;</code>
   * @return The billId.
   */
  long getBillId();

  /**
   * <code>string billingCycle = 52;</code>
   * @return The billingCycle.
   */
  java.lang.String getBillingCycle();
  /**
   * <code>string billingCycle = 52;</code>
   * @return The bytes for billingCycle.
   */
  com.google.protobuf.ByteString
      getBillingCycleBytes();

  /**
   * <code>int32 afterSaleCount = 53;</code>
   * @return The afterSaleCount.
   */
  int getAfterSaleCount();

  /**
   * <code>bool aftersaleApplyEnable = 54;</code>
   * @return The aftersaleApplyEnable.
   */
  boolean getAftersaleApplyEnable();
}
