// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/order/delivery.proto

package com.yuanmai.protobuf.mall.order;

/**
 * Protobuf type {@code mall.protobuf.order.OrderItemMini}
 */
public final class OrderItemMini extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mall.protobuf.order.OrderItemMini)
    OrderItemMiniOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderItemMini.newBuilder() to construct.
  private OrderItemMini(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderItemMini() {
    productName_ = "";
    image_ = "";
    unit_ = 0;
    specs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderItemMini();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.order.Delivery.internal_static_mall_protobuf_order_OrderItemMini_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuanmai.protobuf.mall.order.Delivery.internal_static_mall_protobuf_order_OrderItemMini_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuanmai.protobuf.mall.order.OrderItemMini.class, com.yuanmai.protobuf.mall.order.OrderItemMini.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productName_ = "";
  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBER_FIELD_NUMBER = 3;
  private int number_ = 0;
  /**
   * <code>int32 number = 3;</code>
   * @return The number.
   */
  @java.lang.Override
  public int getNumber() {
    return number_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 4;
  private long amount_ = 0L;
  /**
   * <code>int64 amount = 4;</code>
   * @return The amount.
   */
  @java.lang.Override
  public long getAmount() {
    return amount_;
  }

  public static final int IMAGE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object image_ = "";
  /**
   * <code>string image = 5;</code>
   * @return The image.
   */
  @java.lang.Override
  public java.lang.String getImage() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image_ = s;
      return s;
    }
  }
  /**
   * <code>string image = 5;</code>
   * @return The bytes for image.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageBytes() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      image_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNIT_FIELD_NUMBER = 6;
  private int unit_ = 0;
  /**
   * <code>.mall.protobuf.product.Units unit = 6;</code>
   * @return The enum numeric value on the wire for unit.
   */
  @java.lang.Override public int getUnitValue() {
    return unit_;
  }
  /**
   * <code>.mall.protobuf.product.Units unit = 6;</code>
   * @return The unit.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.product.Units getUnit() {
    com.yuanmai.protobuf.mall.product.Units result = com.yuanmai.protobuf.mall.product.Units.forNumber(unit_);
    return result == null ? com.yuanmai.protobuf.mall.product.Units.UNRECOGNIZED : result;
  }

  public static final int SPECS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.yuanmai.protobuf.mall.order.ItemSpec> specs_;
  /**
   * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.yuanmai.protobuf.mall.order.ItemSpec> getSpecsList() {
    return specs_;
  }
  /**
   * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder> 
      getSpecsOrBuilderList() {
    return specs_;
  }
  /**
   * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
   */
  @java.lang.Override
  public int getSpecsCount() {
    return specs_.size();
  }
  /**
   * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.order.ItemSpec getSpecs(int index) {
    return specs_.get(index);
  }
  /**
   * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder getSpecsOrBuilder(
      int index) {
    return specs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productName_);
    }
    if (number_ != 0) {
      output.writeInt32(3, number_);
    }
    if (amount_ != 0L) {
      output.writeInt64(4, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, image_);
    }
    if (unit_ != com.yuanmai.protobuf.mall.product.Units.PCS.getNumber()) {
      output.writeEnum(6, unit_);
    }
    for (int i = 0; i < specs_.size(); i++) {
      output.writeMessage(7, specs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productName_);
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, number_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, image_);
    }
    if (unit_ != com.yuanmai.protobuf.mall.product.Units.PCS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, unit_);
    }
    for (int i = 0; i < specs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, specs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yuanmai.protobuf.mall.order.OrderItemMini)) {
      return super.equals(obj);
    }
    com.yuanmai.protobuf.mall.order.OrderItemMini other = (com.yuanmai.protobuf.mall.order.OrderItemMini) obj;

    if (getId()
        != other.getId()) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (getNumber()
        != other.getNumber()) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!getImage()
        .equals(other.getImage())) return false;
    if (unit_ != other.unit_) return false;
    if (!getSpecsList()
        .equals(other.getSpecsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getImage().hashCode();
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + unit_;
    if (getSpecsCount() > 0) {
      hash = (37 * hash) + SPECS_FIELD_NUMBER;
      hash = (53 * hash) + getSpecsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.order.OrderItemMini parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yuanmai.protobuf.mall.order.OrderItemMini prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mall.protobuf.order.OrderItemMini}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mall.protobuf.order.OrderItemMini)
      com.yuanmai.protobuf.mall.order.OrderItemMiniOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuanmai.protobuf.mall.order.Delivery.internal_static_mall_protobuf_order_OrderItemMini_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuanmai.protobuf.mall.order.Delivery.internal_static_mall_protobuf_order_OrderItemMini_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuanmai.protobuf.mall.order.OrderItemMini.class, com.yuanmai.protobuf.mall.order.OrderItemMini.Builder.class);
    }

    // Construct using com.yuanmai.protobuf.mall.order.OrderItemMini.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      productName_ = "";
      number_ = 0;
      amount_ = 0L;
      image_ = "";
      unit_ = 0;
      if (specsBuilder_ == null) {
        specs_ = java.util.Collections.emptyList();
      } else {
        specs_ = null;
        specsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuanmai.protobuf.mall.order.Delivery.internal_static_mall_protobuf_order_OrderItemMini_descriptor;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.order.OrderItemMini getDefaultInstanceForType() {
      return com.yuanmai.protobuf.mall.order.OrderItemMini.getDefaultInstance();
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.order.OrderItemMini build() {
      com.yuanmai.protobuf.mall.order.OrderItemMini result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.order.OrderItemMini buildPartial() {
      com.yuanmai.protobuf.mall.order.OrderItemMini result = new com.yuanmai.protobuf.mall.order.OrderItemMini(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yuanmai.protobuf.mall.order.OrderItemMini result) {
      if (specsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          specs_ = java.util.Collections.unmodifiableList(specs_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.specs_ = specs_;
      } else {
        result.specs_ = specsBuilder_.build();
      }
    }

    private void buildPartial0(com.yuanmai.protobuf.mall.order.OrderItemMini result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.productName_ = productName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.number_ = number_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.image_ = image_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.unit_ = unit_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuanmai.protobuf.mall.order.OrderItemMini) {
        return mergeFrom((com.yuanmai.protobuf.mall.order.OrderItemMini)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuanmai.protobuf.mall.order.OrderItemMini other) {
      if (other == com.yuanmai.protobuf.mall.order.OrderItemMini.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getNumber() != 0) {
        setNumber(other.getNumber());
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (!other.getImage().isEmpty()) {
        image_ = other.image_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.unit_ != 0) {
        setUnitValue(other.getUnitValue());
      }
      if (specsBuilder_ == null) {
        if (!other.specs_.isEmpty()) {
          if (specs_.isEmpty()) {
            specs_ = other.specs_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureSpecsIsMutable();
            specs_.addAll(other.specs_);
          }
          onChanged();
        }
      } else {
        if (!other.specs_.isEmpty()) {
          if (specsBuilder_.isEmpty()) {
            specsBuilder_.dispose();
            specsBuilder_ = null;
            specs_ = other.specs_;
            bitField0_ = (bitField0_ & ~0x00000040);
            specsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpecsFieldBuilder() : null;
          } else {
            specsBuilder_.addAllMessages(other.specs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              productName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              number_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              amount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              image_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              unit_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              com.yuanmai.protobuf.mall.order.ItemSpec m =
                  input.readMessage(
                      com.yuanmai.protobuf.mall.order.ItemSpec.parser(),
                      extensionRegistry);
              if (specsBuilder_ == null) {
                ensureSpecsIsMutable();
                specs_.add(m);
              } else {
                specsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object productName_ = "";
    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      productName_ = getDefaultInstance().getProductName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int number_ ;
    /**
     * <code>int32 number = 3;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }
    /**
     * <code>int32 number = 3;</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(int value) {

      number_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      number_ = 0;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <code>int64 amount = 4;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>int64 amount = 4;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {

      amount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      amount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object image_ = "";
    /**
     * <code>string image = 5;</code>
     * @return The image.
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string image = 5;</code>
     * @return The bytes for image.
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image = 5;</code>
     * @param value The image to set.
     * @return This builder for chaining.
     */
    public Builder setImage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      image_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string image = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImage() {
      image_ = getDefaultInstance().getImage();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string image = 5;</code>
     * @param value The bytes for image to set.
     * @return This builder for chaining.
     */
    public Builder setImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      image_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int unit_ = 0;
    /**
     * <code>.mall.protobuf.product.Units unit = 6;</code>
     * @return The enum numeric value on the wire for unit.
     */
    @java.lang.Override public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.mall.protobuf.product.Units unit = 6;</code>
     * @param value The enum numeric value on the wire for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitValue(int value) {
      unit_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.product.Units unit = 6;</code>
     * @return The unit.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Units getUnit() {
      com.yuanmai.protobuf.mall.product.Units result = com.yuanmai.protobuf.mall.product.Units.forNumber(unit_);
      return result == null ? com.yuanmai.protobuf.mall.product.Units.UNRECOGNIZED : result;
    }
    /**
     * <code>.mall.protobuf.product.Units unit = 6;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(com.yuanmai.protobuf.mall.product.Units value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      unit_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mall.protobuf.product.Units unit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      bitField0_ = (bitField0_ & ~0x00000020);
      unit_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.yuanmai.protobuf.mall.order.ItemSpec> specs_ =
      java.util.Collections.emptyList();
    private void ensureSpecsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        specs_ = new java.util.ArrayList<com.yuanmai.protobuf.mall.order.ItemSpec>(specs_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.order.ItemSpec, com.yuanmai.protobuf.mall.order.ItemSpec.Builder, com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder> specsBuilder_;

    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.order.ItemSpec> getSpecsList() {
      if (specsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(specs_);
      } else {
        return specsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public int getSpecsCount() {
      if (specsBuilder_ == null) {
        return specs_.size();
      } else {
        return specsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public com.yuanmai.protobuf.mall.order.ItemSpec getSpecs(int index) {
      if (specsBuilder_ == null) {
        return specs_.get(index);
      } else {
        return specsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder setSpecs(
        int index, com.yuanmai.protobuf.mall.order.ItemSpec value) {
      if (specsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecsIsMutable();
        specs_.set(index, value);
        onChanged();
      } else {
        specsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder setSpecs(
        int index, com.yuanmai.protobuf.mall.order.ItemSpec.Builder builderForValue) {
      if (specsBuilder_ == null) {
        ensureSpecsIsMutable();
        specs_.set(index, builderForValue.build());
        onChanged();
      } else {
        specsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder addSpecs(com.yuanmai.protobuf.mall.order.ItemSpec value) {
      if (specsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecsIsMutable();
        specs_.add(value);
        onChanged();
      } else {
        specsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder addSpecs(
        int index, com.yuanmai.protobuf.mall.order.ItemSpec value) {
      if (specsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpecsIsMutable();
        specs_.add(index, value);
        onChanged();
      } else {
        specsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder addSpecs(
        com.yuanmai.protobuf.mall.order.ItemSpec.Builder builderForValue) {
      if (specsBuilder_ == null) {
        ensureSpecsIsMutable();
        specs_.add(builderForValue.build());
        onChanged();
      } else {
        specsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder addSpecs(
        int index, com.yuanmai.protobuf.mall.order.ItemSpec.Builder builderForValue) {
      if (specsBuilder_ == null) {
        ensureSpecsIsMutable();
        specs_.add(index, builderForValue.build());
        onChanged();
      } else {
        specsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder addAllSpecs(
        java.lang.Iterable<? extends com.yuanmai.protobuf.mall.order.ItemSpec> values) {
      if (specsBuilder_ == null) {
        ensureSpecsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, specs_);
        onChanged();
      } else {
        specsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder clearSpecs() {
      if (specsBuilder_ == null) {
        specs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        specsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public Builder removeSpecs(int index) {
      if (specsBuilder_ == null) {
        ensureSpecsIsMutable();
        specs_.remove(index);
        onChanged();
      } else {
        specsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public com.yuanmai.protobuf.mall.order.ItemSpec.Builder getSpecsBuilder(
        int index) {
      return getSpecsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder getSpecsOrBuilder(
        int index) {
      if (specsBuilder_ == null) {
        return specs_.get(index);  } else {
        return specsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public java.util.List<? extends com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder> 
         getSpecsOrBuilderList() {
      if (specsBuilder_ != null) {
        return specsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(specs_);
      }
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public com.yuanmai.protobuf.mall.order.ItemSpec.Builder addSpecsBuilder() {
      return getSpecsFieldBuilder().addBuilder(
          com.yuanmai.protobuf.mall.order.ItemSpec.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public com.yuanmai.protobuf.mall.order.ItemSpec.Builder addSpecsBuilder(
        int index) {
      return getSpecsFieldBuilder().addBuilder(
          index, com.yuanmai.protobuf.mall.order.ItemSpec.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.order.ItemSpec specs = 7;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.order.ItemSpec.Builder> 
         getSpecsBuilderList() {
      return getSpecsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.order.ItemSpec, com.yuanmai.protobuf.mall.order.ItemSpec.Builder, com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder> 
        getSpecsFieldBuilder() {
      if (specsBuilder_ == null) {
        specsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yuanmai.protobuf.mall.order.ItemSpec, com.yuanmai.protobuf.mall.order.ItemSpec.Builder, com.yuanmai.protobuf.mall.order.ItemSpecOrBuilder>(
                specs_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        specs_ = null;
      }
      return specsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mall.protobuf.order.OrderItemMini)
  }

  // @@protoc_insertion_point(class_scope:mall.protobuf.order.OrderItemMini)
  private static final com.yuanmai.protobuf.mall.order.OrderItemMini DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yuanmai.protobuf.mall.order.OrderItemMini();
  }

  public static com.yuanmai.protobuf.mall.order.OrderItemMini getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderItemMini>
      PARSER = new com.google.protobuf.AbstractParser<OrderItemMini>() {
    @java.lang.Override
    public OrderItemMini parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OrderItemMini> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderItemMini> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yuanmai.protobuf.mall.order.OrderItemMini getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

