// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/product/types.proto

package com.yuanmai.protobuf.mall.product;

/**
 * <pre>
 *属性
 * </pre>
 *
 * Protobuf type {@code mall.protobuf.product.Attr}
 */
public final class Attr extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mall.protobuf.product.Attr)
    AttrOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Attr.newBuilder() to construct.
  private Attr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Attr() {
    category_ = "";
    code_ = "";
    name_ = "";
    vals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Attr();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Attr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Attr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuanmai.protobuf.mall.product.Attr.class, com.yuanmai.protobuf.mall.product.Attr.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int CATEGORYID_FIELD_NUMBER = 2;
  private int categoryId_ = 0;
  /**
   * <code>optional int32 categoryId = 2;</code>
   * @return Whether the categoryId field is set.
   */
  @java.lang.Override
  public boolean hasCategoryId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 categoryId = 2;</code>
   * @return The categoryId.
   */
  @java.lang.Override
  public int getCategoryId() {
    return categoryId_;
  }

  public static final int CATEGORY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <code>string category = 3;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <code>string category = 3;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <code>string code = 4;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 4;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SORTED_FIELD_NUMBER = 6;
  private int sorted_ = 0;
  /**
   * <code>int32 sorted = 6;</code>
   * @return The sorted.
   */
  @java.lang.Override
  public int getSorted() {
    return sorted_;
  }

  public static final int VALS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.yuanmai.protobuf.mall.product.AttrVal> vals_;
  /**
   * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.yuanmai.protobuf.mall.product.AttrVal> getValsList() {
    return vals_;
  }
  /**
   * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yuanmai.protobuf.mall.product.AttrValOrBuilder> 
      getValsOrBuilderList() {
    return vals_;
  }
  /**
   * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
   */
  @java.lang.Override
  public int getValsCount() {
    return vals_.size();
  }
  /**
   * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.product.AttrVal getVals(int index) {
    return vals_.get(index);
  }
  /**
   * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.product.AttrValOrBuilder getValsOrBuilder(
      int index) {
    return vals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, categoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, category_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
    }
    if (sorted_ != 0) {
      output.writeInt32(6, sorted_);
    }
    for (int i = 0; i < vals_.size(); i++) {
      output.writeMessage(7, vals_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, categoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, category_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
    }
    if (sorted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, sorted_);
    }
    for (int i = 0; i < vals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, vals_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yuanmai.protobuf.mall.product.Attr)) {
      return super.equals(obj);
    }
    com.yuanmai.protobuf.mall.product.Attr other = (com.yuanmai.protobuf.mall.product.Attr) obj;

    if (getId()
        != other.getId()) return false;
    if (hasCategoryId() != other.hasCategoryId()) return false;
    if (hasCategoryId()) {
      if (getCategoryId()
          != other.getCategoryId()) return false;
    }
    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getSorted()
        != other.getSorted()) return false;
    if (!getValsList()
        .equals(other.getValsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasCategoryId()) {
      hash = (37 * hash) + CATEGORYID_FIELD_NUMBER;
      hash = (53 * hash) + getCategoryId();
    }
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SORTED_FIELD_NUMBER;
    hash = (53 * hash) + getSorted();
    if (getValsCount() > 0) {
      hash = (37 * hash) + VALS_FIELD_NUMBER;
      hash = (53 * hash) + getValsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yuanmai.protobuf.mall.product.Attr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yuanmai.protobuf.mall.product.Attr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.product.Attr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yuanmai.protobuf.mall.product.Attr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *属性
   * </pre>
   *
   * Protobuf type {@code mall.protobuf.product.Attr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mall.protobuf.product.Attr)
      com.yuanmai.protobuf.mall.product.AttrOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Attr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Attr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuanmai.protobuf.mall.product.Attr.class, com.yuanmai.protobuf.mall.product.Attr.Builder.class);
    }

    // Construct using com.yuanmai.protobuf.mall.product.Attr.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      categoryId_ = 0;
      category_ = "";
      code_ = "";
      name_ = "";
      sorted_ = 0;
      if (valsBuilder_ == null) {
        vals_ = java.util.Collections.emptyList();
      } else {
        vals_ = null;
        valsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Attr_descriptor;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Attr getDefaultInstanceForType() {
      return com.yuanmai.protobuf.mall.product.Attr.getDefaultInstance();
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Attr build() {
      com.yuanmai.protobuf.mall.product.Attr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Attr buildPartial() {
      com.yuanmai.protobuf.mall.product.Attr result = new com.yuanmai.protobuf.mall.product.Attr(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yuanmai.protobuf.mall.product.Attr result) {
      if (valsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          vals_ = java.util.Collections.unmodifiableList(vals_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.vals_ = vals_;
      } else {
        result.vals_ = valsBuilder_.build();
      }
    }

    private void buildPartial0(com.yuanmai.protobuf.mall.product.Attr result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.categoryId_ = categoryId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.category_ = category_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.sorted_ = sorted_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuanmai.protobuf.mall.product.Attr) {
        return mergeFrom((com.yuanmai.protobuf.mall.product.Attr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuanmai.protobuf.mall.product.Attr other) {
      if (other == com.yuanmai.protobuf.mall.product.Attr.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasCategoryId()) {
        setCategoryId(other.getCategoryId());
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getSorted() != 0) {
        setSorted(other.getSorted());
      }
      if (valsBuilder_ == null) {
        if (!other.vals_.isEmpty()) {
          if (vals_.isEmpty()) {
            vals_ = other.vals_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureValsIsMutable();
            vals_.addAll(other.vals_);
          }
          onChanged();
        }
      } else {
        if (!other.vals_.isEmpty()) {
          if (valsBuilder_.isEmpty()) {
            valsBuilder_.dispose();
            valsBuilder_ = null;
            vals_ = other.vals_;
            bitField0_ = (bitField0_ & ~0x00000040);
            valsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValsFieldBuilder() : null;
          } else {
            valsBuilder_.addAllMessages(other.vals_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              categoryId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              sorted_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              com.yuanmai.protobuf.mall.product.AttrVal m =
                  input.readMessage(
                      com.yuanmai.protobuf.mall.product.AttrVal.parser(),
                      extensionRegistry);
              if (valsBuilder_ == null) {
                ensureValsIsMutable();
                vals_.add(m);
              } else {
                valsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int categoryId_ ;
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @return Whether the categoryId field is set.
     */
    @java.lang.Override
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public int getCategoryId() {
      return categoryId_;
    }
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @param value The categoryId to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryId(int value) {

      categoryId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      categoryId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <code>string category = 3;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category = 3;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category = 3;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string category = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string category = 3;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 4;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 4;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 4;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string code = 4;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 5;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 5;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int sorted_ ;
    /**
     * <code>int32 sorted = 6;</code>
     * @return The sorted.
     */
    @java.lang.Override
    public int getSorted() {
      return sorted_;
    }
    /**
     * <code>int32 sorted = 6;</code>
     * @param value The sorted to set.
     * @return This builder for chaining.
     */
    public Builder setSorted(int value) {

      sorted_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sorted = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSorted() {
      bitField0_ = (bitField0_ & ~0x00000020);
      sorted_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.yuanmai.protobuf.mall.product.AttrVal> vals_ =
      java.util.Collections.emptyList();
    private void ensureValsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        vals_ = new java.util.ArrayList<com.yuanmai.protobuf.mall.product.AttrVal>(vals_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.product.AttrVal, com.yuanmai.protobuf.mall.product.AttrVal.Builder, com.yuanmai.protobuf.mall.product.AttrValOrBuilder> valsBuilder_;

    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.product.AttrVal> getValsList() {
      if (valsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vals_);
      } else {
        return valsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public int getValsCount() {
      if (valsBuilder_ == null) {
        return vals_.size();
      } else {
        return valsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public com.yuanmai.protobuf.mall.product.AttrVal getVals(int index) {
      if (valsBuilder_ == null) {
        return vals_.get(index);
      } else {
        return valsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder setVals(
        int index, com.yuanmai.protobuf.mall.product.AttrVal value) {
      if (valsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValsIsMutable();
        vals_.set(index, value);
        onChanged();
      } else {
        valsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder setVals(
        int index, com.yuanmai.protobuf.mall.product.AttrVal.Builder builderForValue) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.set(index, builderForValue.build());
        onChanged();
      } else {
        valsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder addVals(com.yuanmai.protobuf.mall.product.AttrVal value) {
      if (valsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValsIsMutable();
        vals_.add(value);
        onChanged();
      } else {
        valsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder addVals(
        int index, com.yuanmai.protobuf.mall.product.AttrVal value) {
      if (valsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValsIsMutable();
        vals_.add(index, value);
        onChanged();
      } else {
        valsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder addVals(
        com.yuanmai.protobuf.mall.product.AttrVal.Builder builderForValue) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.add(builderForValue.build());
        onChanged();
      } else {
        valsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder addVals(
        int index, com.yuanmai.protobuf.mall.product.AttrVal.Builder builderForValue) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.add(index, builderForValue.build());
        onChanged();
      } else {
        valsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder addAllVals(
        java.lang.Iterable<? extends com.yuanmai.protobuf.mall.product.AttrVal> values) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vals_);
        onChanged();
      } else {
        valsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder clearVals() {
      if (valsBuilder_ == null) {
        vals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        valsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public Builder removeVals(int index) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.remove(index);
        onChanged();
      } else {
        valsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public com.yuanmai.protobuf.mall.product.AttrVal.Builder getValsBuilder(
        int index) {
      return getValsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public com.yuanmai.protobuf.mall.product.AttrValOrBuilder getValsOrBuilder(
        int index) {
      if (valsBuilder_ == null) {
        return vals_.get(index);  } else {
        return valsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public java.util.List<? extends com.yuanmai.protobuf.mall.product.AttrValOrBuilder> 
         getValsOrBuilderList() {
      if (valsBuilder_ != null) {
        return valsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vals_);
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public com.yuanmai.protobuf.mall.product.AttrVal.Builder addValsBuilder() {
      return getValsFieldBuilder().addBuilder(
          com.yuanmai.protobuf.mall.product.AttrVal.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public com.yuanmai.protobuf.mall.product.AttrVal.Builder addValsBuilder(
        int index) {
      return getValsFieldBuilder().addBuilder(
          index, com.yuanmai.protobuf.mall.product.AttrVal.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.product.AttrVal vals = 7;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.product.AttrVal.Builder> 
         getValsBuilderList() {
      return getValsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.product.AttrVal, com.yuanmai.protobuf.mall.product.AttrVal.Builder, com.yuanmai.protobuf.mall.product.AttrValOrBuilder> 
        getValsFieldBuilder() {
      if (valsBuilder_ == null) {
        valsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yuanmai.protobuf.mall.product.AttrVal, com.yuanmai.protobuf.mall.product.AttrVal.Builder, com.yuanmai.protobuf.mall.product.AttrValOrBuilder>(
                vals_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        vals_ = null;
      }
      return valsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mall.protobuf.product.Attr)
  }

  // @@protoc_insertion_point(class_scope:mall.protobuf.product.Attr)
  private static final com.yuanmai.protobuf.mall.product.Attr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yuanmai.protobuf.mall.product.Attr();
  }

  public static com.yuanmai.protobuf.mall.product.Attr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Attr>
      PARSER = new com.google.protobuf.AbstractParser<Attr>() {
    @java.lang.Override
    public Attr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Attr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Attr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yuanmai.protobuf.mall.product.Attr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

