// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/product/types.proto

package com.yuanmai.protobuf.mall.product;

public interface CategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mall.protobuf.product.Category)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 parentId = 2;</code>
   * @return The parentId.
   */
  int getParentId();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string code = 4;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>optional string code = 4;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 4;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string icon = 5;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>optional string icon = 5;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>optional string icon = 5;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>optional string image = 6;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>optional string image = 6;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>optional string image = 6;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>bool enabled = 7;</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>int32 sorted = 8;</code>
   * @return The sorted.
   */
  int getSorted();

  /**
   * <code>int32 level = 9;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>repeated .mall.protobuf.product.Category children = 10;</code>
   */
  java.util.List<com.yuanmai.protobuf.mall.product.Category> 
      getChildrenList();
  /**
   * <code>repeated .mall.protobuf.product.Category children = 10;</code>
   */
  com.yuanmai.protobuf.mall.product.Category getChildren(int index);
  /**
   * <code>repeated .mall.protobuf.product.Category children = 10;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .mall.protobuf.product.Category children = 10;</code>
   */
  java.util.List<? extends com.yuanmai.protobuf.mall.product.CategoryOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .mall.protobuf.product.Category children = 10;</code>
   */
  com.yuanmai.protobuf.mall.product.CategoryOrBuilder getChildrenOrBuilder(
      int index);
}
