// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/product/types.proto

package com.yuanmai.protobuf.mall.product;

/**
 * Protobuf type {@code mall.protobuf.product.Spec}
 */
public final class Spec extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mall.protobuf.product.Spec)
    SpecOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Spec.newBuilder() to construct.
  private Spec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Spec() {
    type_ = 0;
    name_ = "";
    code_ = "";
    vals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Spec();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Spec_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Spec_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuanmai.protobuf.mall.product.Spec.class, com.yuanmai.protobuf.mall.product.Spec.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int CATEGORYID_FIELD_NUMBER = 2;
  private int categoryId_ = 0;
  /**
   * <code>optional int32 categoryId = 2;</code>
   * @return Whether the categoryId field is set.
   */
  @java.lang.Override
  public boolean hasCategoryId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 categoryId = 2;</code>
   * @return The categoryId.
   */
  @java.lang.Override
  public int getCategoryId() {
    return categoryId_;
  }

  public static final int PRODUCTID_FIELD_NUMBER = 3;
  private long productId_ = 0L;
  /**
   * <code>optional int64 productId = 3;</code>
   * @return Whether the productId field is set.
   */
  @java.lang.Override
  public boolean hasProductId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 productId = 3;</code>
   * @return The productId.
   */
  @java.lang.Override
  public long getProductId() {
    return productId_;
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_ = 0;
  /**
   * <code>optional .mall.protobuf.product.InputType type = 4;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override public boolean hasType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .mall.protobuf.product.InputType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .mall.protobuf.product.InputType type = 4;</code>
   * @return The type.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.product.InputType getType() {
    com.yuanmai.protobuf.mall.product.InputType result = com.yuanmai.protobuf.mall.product.InputType.forNumber(type_);
    return result == null ? com.yuanmai.protobuf.mall.product.InputType.UNRECOGNIZED : result;
  }

  public static final int INPUT_FIELD_NUMBER = 5;
  private boolean input_ = false;
  /**
   * <code>bool input = 5;</code>
   * @return The input.
   */
  @java.lang.Override
  public boolean getInput() {
    return input_;
  }

  public static final int NAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 6;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <code>string code = 7;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 7;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SORTED_FIELD_NUMBER = 8;
  private int sorted_ = 0;
  /**
   * <code>int32 sorted = 8;</code>
   * @return The sorted.
   */
  @java.lang.Override
  public int getSorted() {
    return sorted_;
  }

  public static final int VALS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<com.yuanmai.protobuf.mall.product.SpecVal> vals_;
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  @java.lang.Override
  public java.util.List<com.yuanmai.protobuf.mall.product.SpecVal> getValsList() {
    return vals_;
  }
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yuanmai.protobuf.mall.product.SpecValOrBuilder> 
      getValsOrBuilderList() {
    return vals_;
  }
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  @java.lang.Override
  public int getValsCount() {
    return vals_.size();
  }
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.product.SpecVal getVals(int index) {
    return vals_.get(index);
  }
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.product.SpecValOrBuilder getValsOrBuilder(
      int index) {
    return vals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, categoryId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(3, productId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(4, type_);
    }
    if (input_ != false) {
      output.writeBool(5, input_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, code_);
    }
    if (sorted_ != 0) {
      output.writeInt32(8, sorted_);
    }
    for (int i = 0; i < vals_.size(); i++) {
      output.writeMessage(9, vals_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, categoryId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, productId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (input_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, input_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, code_);
    }
    if (sorted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, sorted_);
    }
    for (int i = 0; i < vals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, vals_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yuanmai.protobuf.mall.product.Spec)) {
      return super.equals(obj);
    }
    com.yuanmai.protobuf.mall.product.Spec other = (com.yuanmai.protobuf.mall.product.Spec) obj;

    if (getId()
        != other.getId()) return false;
    if (hasCategoryId() != other.hasCategoryId()) return false;
    if (hasCategoryId()) {
      if (getCategoryId()
          != other.getCategoryId()) return false;
    }
    if (hasProductId() != other.hasProductId()) return false;
    if (hasProductId()) {
      if (getProductId()
          != other.getProductId()) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (getInput()
        != other.getInput()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (getSorted()
        != other.getSorted()) return false;
    if (!getValsList()
        .equals(other.getValsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasCategoryId()) {
      hash = (37 * hash) + CATEGORYID_FIELD_NUMBER;
      hash = (53 * hash) + getCategoryId();
    }
    if (hasProductId()) {
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductId());
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    hash = (37 * hash) + INPUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInput());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + SORTED_FIELD_NUMBER;
    hash = (53 * hash) + getSorted();
    if (getValsCount() > 0) {
      hash = (37 * hash) + VALS_FIELD_NUMBER;
      hash = (53 * hash) + getValsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yuanmai.protobuf.mall.product.Spec parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yuanmai.protobuf.mall.product.Spec parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.product.Spec parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yuanmai.protobuf.mall.product.Spec prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mall.protobuf.product.Spec}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mall.protobuf.product.Spec)
      com.yuanmai.protobuf.mall.product.SpecOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Spec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Spec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuanmai.protobuf.mall.product.Spec.class, com.yuanmai.protobuf.mall.product.Spec.Builder.class);
    }

    // Construct using com.yuanmai.protobuf.mall.product.Spec.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      categoryId_ = 0;
      productId_ = 0L;
      type_ = 0;
      input_ = false;
      name_ = "";
      code_ = "";
      sorted_ = 0;
      if (valsBuilder_ == null) {
        vals_ = java.util.Collections.emptyList();
      } else {
        vals_ = null;
        valsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuanmai.protobuf.mall.product.Types.internal_static_mall_protobuf_product_Spec_descriptor;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Spec getDefaultInstanceForType() {
      return com.yuanmai.protobuf.mall.product.Spec.getDefaultInstance();
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Spec build() {
      com.yuanmai.protobuf.mall.product.Spec result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.Spec buildPartial() {
      com.yuanmai.protobuf.mall.product.Spec result = new com.yuanmai.protobuf.mall.product.Spec(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yuanmai.protobuf.mall.product.Spec result) {
      if (valsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          vals_ = java.util.Collections.unmodifiableList(vals_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.vals_ = vals_;
      } else {
        result.vals_ = valsBuilder_.build();
      }
    }

    private void buildPartial0(com.yuanmai.protobuf.mall.product.Spec result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.categoryId_ = categoryId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.productId_ = productId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.input_ = input_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sorted_ = sorted_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuanmai.protobuf.mall.product.Spec) {
        return mergeFrom((com.yuanmai.protobuf.mall.product.Spec)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuanmai.protobuf.mall.product.Spec other) {
      if (other == com.yuanmai.protobuf.mall.product.Spec.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasCategoryId()) {
        setCategoryId(other.getCategoryId());
      }
      if (other.hasProductId()) {
        setProductId(other.getProductId());
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.getInput() != false) {
        setInput(other.getInput());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getSorted() != 0) {
        setSorted(other.getSorted());
      }
      if (valsBuilder_ == null) {
        if (!other.vals_.isEmpty()) {
          if (vals_.isEmpty()) {
            vals_ = other.vals_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureValsIsMutable();
            vals_.addAll(other.vals_);
          }
          onChanged();
        }
      } else {
        if (!other.vals_.isEmpty()) {
          if (valsBuilder_.isEmpty()) {
            valsBuilder_.dispose();
            valsBuilder_ = null;
            vals_ = other.vals_;
            bitField0_ = (bitField0_ & ~0x00000100);
            valsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValsFieldBuilder() : null;
          } else {
            valsBuilder_.addAllMessages(other.vals_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              categoryId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              productId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              input_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              sorted_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              com.yuanmai.protobuf.mall.product.SpecVal m =
                  input.readMessage(
                      com.yuanmai.protobuf.mall.product.SpecVal.parser(),
                      extensionRegistry);
              if (valsBuilder_ == null) {
                ensureValsIsMutable();
                vals_.add(m);
              } else {
                valsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int categoryId_ ;
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @return Whether the categoryId field is set.
     */
    @java.lang.Override
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public int getCategoryId() {
      return categoryId_;
    }
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @param value The categoryId to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryId(int value) {

      categoryId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 categoryId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      categoryId_ = 0;
      onChanged();
      return this;
    }

    private long productId_ ;
    /**
     * <code>optional int64 productId = 3;</code>
     * @return Whether the productId field is set.
     */
    @java.lang.Override
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 productId = 3;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }
    /**
     * <code>optional int64 productId = 3;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(long value) {

      productId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 productId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      productId_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .mall.protobuf.product.InputType type = 4;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .mall.protobuf.product.InputType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .mall.protobuf.product.InputType type = 4;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .mall.protobuf.product.InputType type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.product.InputType getType() {
      com.yuanmai.protobuf.mall.product.InputType result = com.yuanmai.protobuf.mall.product.InputType.forNumber(type_);
      return result == null ? com.yuanmai.protobuf.mall.product.InputType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .mall.protobuf.product.InputType type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.yuanmai.protobuf.mall.product.InputType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .mall.protobuf.product.InputType type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = 0;
      onChanged();
      return this;
    }

    private boolean input_ ;
    /**
     * <code>bool input = 5;</code>
     * @return The input.
     */
    @java.lang.Override
    public boolean getInput() {
      return input_;
    }
    /**
     * <code>bool input = 5;</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(boolean value) {

      input_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool input = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      bitField0_ = (bitField0_ & ~0x00000010);
      input_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 6;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 6;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 6;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 6;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 7;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 7;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 7;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string code = 7;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int sorted_ ;
    /**
     * <code>int32 sorted = 8;</code>
     * @return The sorted.
     */
    @java.lang.Override
    public int getSorted() {
      return sorted_;
    }
    /**
     * <code>int32 sorted = 8;</code>
     * @param value The sorted to set.
     * @return This builder for chaining.
     */
    public Builder setSorted(int value) {

      sorted_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sorted = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSorted() {
      bitField0_ = (bitField0_ & ~0x00000080);
      sorted_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.yuanmai.protobuf.mall.product.SpecVal> vals_ =
      java.util.Collections.emptyList();
    private void ensureValsIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        vals_ = new java.util.ArrayList<com.yuanmai.protobuf.mall.product.SpecVal>(vals_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.product.SpecVal, com.yuanmai.protobuf.mall.product.SpecVal.Builder, com.yuanmai.protobuf.mall.product.SpecValOrBuilder> valsBuilder_;

    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.product.SpecVal> getValsList() {
      if (valsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vals_);
      } else {
        return valsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public int getValsCount() {
      if (valsBuilder_ == null) {
        return vals_.size();
      } else {
        return valsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public com.yuanmai.protobuf.mall.product.SpecVal getVals(int index) {
      if (valsBuilder_ == null) {
        return vals_.get(index);
      } else {
        return valsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder setVals(
        int index, com.yuanmai.protobuf.mall.product.SpecVal value) {
      if (valsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValsIsMutable();
        vals_.set(index, value);
        onChanged();
      } else {
        valsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder setVals(
        int index, com.yuanmai.protobuf.mall.product.SpecVal.Builder builderForValue) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.set(index, builderForValue.build());
        onChanged();
      } else {
        valsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder addVals(com.yuanmai.protobuf.mall.product.SpecVal value) {
      if (valsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValsIsMutable();
        vals_.add(value);
        onChanged();
      } else {
        valsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder addVals(
        int index, com.yuanmai.protobuf.mall.product.SpecVal value) {
      if (valsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValsIsMutable();
        vals_.add(index, value);
        onChanged();
      } else {
        valsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder addVals(
        com.yuanmai.protobuf.mall.product.SpecVal.Builder builderForValue) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.add(builderForValue.build());
        onChanged();
      } else {
        valsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder addVals(
        int index, com.yuanmai.protobuf.mall.product.SpecVal.Builder builderForValue) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.add(index, builderForValue.build());
        onChanged();
      } else {
        valsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder addAllVals(
        java.lang.Iterable<? extends com.yuanmai.protobuf.mall.product.SpecVal> values) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vals_);
        onChanged();
      } else {
        valsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder clearVals() {
      if (valsBuilder_ == null) {
        vals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        valsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public Builder removeVals(int index) {
      if (valsBuilder_ == null) {
        ensureValsIsMutable();
        vals_.remove(index);
        onChanged();
      } else {
        valsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public com.yuanmai.protobuf.mall.product.SpecVal.Builder getValsBuilder(
        int index) {
      return getValsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public com.yuanmai.protobuf.mall.product.SpecValOrBuilder getValsOrBuilder(
        int index) {
      if (valsBuilder_ == null) {
        return vals_.get(index);  } else {
        return valsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public java.util.List<? extends com.yuanmai.protobuf.mall.product.SpecValOrBuilder> 
         getValsOrBuilderList() {
      if (valsBuilder_ != null) {
        return valsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vals_);
      }
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public com.yuanmai.protobuf.mall.product.SpecVal.Builder addValsBuilder() {
      return getValsFieldBuilder().addBuilder(
          com.yuanmai.protobuf.mall.product.SpecVal.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public com.yuanmai.protobuf.mall.product.SpecVal.Builder addValsBuilder(
        int index) {
      return getValsFieldBuilder().addBuilder(
          index, com.yuanmai.protobuf.mall.product.SpecVal.getDefaultInstance());
    }
    /**
     * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.product.SpecVal.Builder> 
         getValsBuilderList() {
      return getValsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.product.SpecVal, com.yuanmai.protobuf.mall.product.SpecVal.Builder, com.yuanmai.protobuf.mall.product.SpecValOrBuilder> 
        getValsFieldBuilder() {
      if (valsBuilder_ == null) {
        valsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yuanmai.protobuf.mall.product.SpecVal, com.yuanmai.protobuf.mall.product.SpecVal.Builder, com.yuanmai.protobuf.mall.product.SpecValOrBuilder>(
                vals_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        vals_ = null;
      }
      return valsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mall.protobuf.product.Spec)
  }

  // @@protoc_insertion_point(class_scope:mall.protobuf.product.Spec)
  private static final com.yuanmai.protobuf.mall.product.Spec DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yuanmai.protobuf.mall.product.Spec();
  }

  public static com.yuanmai.protobuf.mall.product.Spec getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Spec>
      PARSER = new com.google.protobuf.AbstractParser<Spec>() {
    @java.lang.Override
    public Spec parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Spec> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Spec> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yuanmai.protobuf.mall.product.Spec getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

