// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/product/types.proto

package com.yuanmai.protobuf.mall.product;

public interface SpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mall.protobuf.product.Spec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional int32 categoryId = 2;</code>
   * @return Whether the categoryId field is set.
   */
  boolean hasCategoryId();
  /**
   * <code>optional int32 categoryId = 2;</code>
   * @return The categoryId.
   */
  int getCategoryId();

  /**
   * <code>optional int64 productId = 3;</code>
   * @return Whether the productId field is set.
   */
  boolean hasProductId();
  /**
   * <code>optional int64 productId = 3;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>optional .mall.protobuf.product.InputType type = 4;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional .mall.protobuf.product.InputType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>optional .mall.protobuf.product.InputType type = 4;</code>
   * @return The type.
   */
  com.yuanmai.protobuf.mall.product.InputType getType();

  /**
   * <code>bool input = 5;</code>
   * @return The input.
   */
  boolean getInput();

  /**
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 7;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 7;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>int32 sorted = 8;</code>
   * @return The sorted.
   */
  int getSorted();

  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  java.util.List<com.yuanmai.protobuf.mall.product.SpecVal> 
      getValsList();
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  com.yuanmai.protobuf.mall.product.SpecVal getVals(int index);
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  int getValsCount();
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  java.util.List<? extends com.yuanmai.protobuf.mall.product.SpecValOrBuilder> 
      getValsOrBuilderList();
  /**
   * <code>repeated .mall.protobuf.product.SpecVal vals = 9;</code>
   */
  com.yuanmai.protobuf.mall.product.SpecValOrBuilder getValsOrBuilder(
      int index);
}
