// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/product/types.proto

package com.yuanmai.protobuf.mall.product;

/**
 * <pre>
 *规格类型
 * </pre>
 *
 * Protobuf enum {@code mall.protobuf.product.SpecType}
 */
public enum SpecType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *    单规格
   * </pre>
   *
   * <code>GENERAL = 0;</code>
   */
  GENERAL(0),
  /**
   * <pre>
   *    多规格
   * </pre>
   *
   * <code>MULTIPLE = 1;</code>
   */
  MULTIPLE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *    单规格
   * </pre>
   *
   * <code>GENERAL = 0;</code>
   */
  public static final int GENERAL_VALUE = 0;
  /**
   * <pre>
   *    多规格
   * </pre>
   *
   * <code>MULTIPLE = 1;</code>
   */
  public static final int MULTIPLE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SpecType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SpecType forNumber(int value) {
    switch (value) {
      case 0: return GENERAL;
      case 1: return MULTIPLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SpecType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SpecType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SpecType>() {
          public SpecType findValueByNumber(int number) {
            return SpecType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.product.Types.getDescriptor().getEnumTypes().get(5);
  }

  private static final SpecType[] VALUES = values();

  public static SpecType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SpecType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:mall.protobuf.product.SpecType)
}

