// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mall/protobuf/aftersale/types.proto

package com.yuanmai.protobuf.mall.aftersale;

/**
 * Protobuf type {@code mall.protobuf.aftersale.AfterSaleOrderInfo}
 */
public final class AfterSaleOrderInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mall.protobuf.aftersale.AfterSaleOrderInfo)
    AfterSaleOrderInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AfterSaleOrderInfo.newBuilder() to construct.
  private AfterSaleOrderInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AfterSaleOrderInfo() {
    orderNumber_ = "";
    parentOrderNumber_ = "";
    originOrderNumber_ = "";
    type_ = 0;
    state_ = 0;
    temporaryState_ = 0;
    approvalState_ = 0;
    description_ = "";
    remark_ = "";
    operator_ = "";
    items_ = java.util.Collections.emptyList();
    address_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AfterSaleOrderInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yuanmai.protobuf.mall.aftersale.Types.internal_static_mall_protobuf_aftersale_AfterSaleOrderInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yuanmai.protobuf.mall.aftersale.Types.internal_static_mall_protobuf_aftersale_AfterSaleOrderInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.class, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int SUPPLIERID_FIELD_NUMBER = 2;
  private int supplierId_ = 0;
  /**
   * <pre>
   * 供货商ID
   * </pre>
   *
   * <code>int32 supplierId = 2;</code>
   * @return The supplierId.
   */
  @java.lang.Override
  public int getSupplierId() {
    return supplierId_;
  }

  public static final int APPROVALID_FIELD_NUMBER = 3;
  private long approvalId_ = 0L;
  /**
   * <pre>
   * 审核ID
   * </pre>
   *
   * <code>int64 approvalId = 3;</code>
   * @return The approvalId.
   */
  @java.lang.Override
  public long getApprovalId() {
    return approvalId_;
  }

  public static final int ORDERNUMBER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orderNumber_ = "";
  /**
   * <pre>
   * 售后订单编号
   * </pre>
   *
   * <code>string orderNumber = 4;</code>
   * @return The orderNumber.
   */
  @java.lang.Override
  public java.lang.String getOrderNumber() {
    java.lang.Object ref = orderNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 售后订单编号
   * </pre>
   *
   * <code>string orderNumber = 4;</code>
   * @return The bytes for orderNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrderNumberBytes() {
    java.lang.Object ref = orderNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTORDERNUMBER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentOrderNumber_ = "";
  /**
   * <pre>
   * 父售后订单那编号
   * </pre>
   *
   * <code>string parentOrderNumber = 5;</code>
   * @return The parentOrderNumber.
   */
  @java.lang.Override
  public java.lang.String getParentOrderNumber() {
    java.lang.Object ref = parentOrderNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentOrderNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 父售后订单那编号
   * </pre>
   *
   * <code>string parentOrderNumber = 5;</code>
   * @return The bytes for parentOrderNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentOrderNumberBytes() {
    java.lang.Object ref = parentOrderNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentOrderNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINORDERID_FIELD_NUMBER = 6;
  private long originOrderId_ = 0L;
  /**
   * <pre>
   * 订单ID
   * </pre>
   *
   * <code>int64 originOrderId = 6;</code>
   * @return The originOrderId.
   */
  @java.lang.Override
  public long getOriginOrderId() {
    return originOrderId_;
  }

  public static final int ORIGINORDERNUMBER_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originOrderNumber_ = "";
  /**
   * <pre>
   * 订单编号
   * </pre>
   *
   * <code>string originOrderNumber = 7;</code>
   * @return The originOrderNumber.
   */
  @java.lang.Override
  public java.lang.String getOriginOrderNumber() {
    java.lang.Object ref = originOrderNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originOrderNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 订单编号
   * </pre>
   *
   * <code>string originOrderNumber = 7;</code>
   * @return The bytes for originOrderNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginOrderNumberBytes() {
    java.lang.Object ref = originOrderNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originOrderNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 8;
  private int type_ = 0;
  /**
   * <pre>
   * 退款类型 0=退款,1=退货退款,2=换货
   * </pre>
   *
   * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 退款类型 0=退款,1=退货退款,2=换货
   * </pre>
   *
   * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
   * @return The type.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.aftersale.AfterSaleType getType() {
    com.yuanmai.protobuf.mall.aftersale.AfterSaleType result = com.yuanmai.protobuf.mall.aftersale.AfterSaleType.forNumber(type_);
    return result == null ? com.yuanmai.protobuf.mall.aftersale.AfterSaleType.UNRECOGNIZED : result;
  }

  public static final int STATE_FIELD_NUMBER = 9;
  private int state_ = 0;
  /**
   * <pre>
   * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
   * </pre>
   *
   * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <pre>
   * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
   * </pre>
   *
   * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
   * @return The state.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.aftersale.AfterState getState() {
    com.yuanmai.protobuf.mall.aftersale.AfterState result = com.yuanmai.protobuf.mall.aftersale.AfterState.forNumber(state_);
    return result == null ? com.yuanmai.protobuf.mall.aftersale.AfterState.UNRECOGNIZED : result;
  }

  public static final int TEMPORARYSTATE_FIELD_NUMBER = 10;
  private int temporaryState_ = 0;
  /**
   * <pre>
   * 临时订单状态 记录提交售后时，订单状态
   * </pre>
   *
   * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
   * @return The enum numeric value on the wire for temporaryState.
   */
  @java.lang.Override public int getTemporaryStateValue() {
    return temporaryState_;
  }
  /**
   * <pre>
   * 临时订单状态 记录提交售后时，订单状态
   * </pre>
   *
   * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
   * @return The temporaryState.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.order.OrderState getTemporaryState() {
    com.yuanmai.protobuf.mall.order.OrderState result = com.yuanmai.protobuf.mall.order.OrderState.forNumber(temporaryState_);
    return result == null ? com.yuanmai.protobuf.mall.order.OrderState.UNRECOGNIZED : result;
  }

  public static final int APPROVALSTATE_FIELD_NUMBER = 11;
  private int approvalState_ = 0;
  /**
   * <pre>
   * 审核状态
   * </pre>
   *
   * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
   * @return The enum numeric value on the wire for approvalState.
   */
  @java.lang.Override public int getApprovalStateValue() {
    return approvalState_;
  }
  /**
   * <pre>
   * 审核状态
   * </pre>
   *
   * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
   * @return The approvalState.
   */
  @java.lang.Override public com.yuanmai.protobuf.mall.approval.ApprovalStatus getApprovalState() {
    com.yuanmai.protobuf.mall.approval.ApprovalStatus result = com.yuanmai.protobuf.mall.approval.ApprovalStatus.forNumber(approvalState_);
    return result == null ? com.yuanmai.protobuf.mall.approval.ApprovalStatus.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_FIELD_NUMBER = 12;
  private long amount_ = 0L;
  /**
   * <pre>
   * 总金额
   * </pre>
   *
   * <code>int64 amount = 12;</code>
   * @return The amount.
   */
  @java.lang.Override
  public long getAmount() {
    return amount_;
  }

  public static final int PAYAMOUNT_FIELD_NUMBER = 13;
  private long payAmount_ = 0L;
  /**
   * <pre>
   * 实际支付金额
   * </pre>
   *
   * <code>int64 payAmount = 13;</code>
   * @return The payAmount.
   */
  @java.lang.Override
  public long getPayAmount() {
    return payAmount_;
  }

  public static final int REASON_FIELD_NUMBER = 14;
  private int reason_ = 0;
  /**
   * <pre>
   * 客户 选择原因
   * </pre>
   *
   * <code>int32 reason = 14;</code>
   * @return The reason.
   */
  @java.lang.Override
  public int getReason() {
    return reason_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * 描述
   * </pre>
   *
   * <code>string description = 15;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 描述
   * </pre>
   *
   * <code>string description = 15;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMARK_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private volatile java.lang.Object remark_ = "";
  /**
   * <pre>
   * 备注 客服填写
   * </pre>
   *
   * <code>string remark = 16;</code>
   * @return The remark.
   */
  @java.lang.Override
  public java.lang.String getRemark() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      remark_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 备注 客服填写
   * </pre>
   *
   * <code>string remark = 16;</code>
   * @return The bytes for remark.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRemarkBytes() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATORID_FIELD_NUMBER = 17;
  private long operatorId_ = 0L;
  /**
   * <pre>
   * 操作人
   * </pre>
   *
   * <code>int64 operatorId = 17;</code>
   * @return The operatorId.
   */
  @java.lang.Override
  public long getOperatorId() {
    return operatorId_;
  }

  public static final int OPERATOR_FIELD_NUMBER = 18;
  @SuppressWarnings("serial")
  private volatile java.lang.Object operator_ = "";
  /**
   * <pre>
   * 操作人姓名
   * </pre>
   *
   * <code>string operator = 18;</code>
   * @return The operator.
   */
  @java.lang.Override
  public java.lang.String getOperator() {
    java.lang.Object ref = operator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operator_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 操作人姓名
   * </pre>
   *
   * <code>string operator = 18;</code>
   * @return The bytes for operator.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperatorBytes() {
    java.lang.Object ref = operator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEMS_FIELD_NUMBER = 19;
  @SuppressWarnings("serial")
  private java.util.List<com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem> items_;
  /**
   * <pre>
   * 售后商品
   * </pre>
   *
   * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
   */
  @java.lang.Override
  public java.util.List<com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * 售后商品
   * </pre>
   *
   * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * 售后商品
   * </pre>
   *
   * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * 售后商品
   * </pre>
   *
   * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * 售后商品
   * </pre>
   *
   * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
   */
  @java.lang.Override
  public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int ADDRESS_FIELD_NUMBER = 20;
  @SuppressWarnings("serial")
  private volatile java.lang.Object address_ = "";
  /**
   * <code>string address = 20;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 20;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (supplierId_ != 0) {
      output.writeInt32(2, supplierId_);
    }
    if (approvalId_ != 0L) {
      output.writeInt64(3, approvalId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentOrderNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parentOrderNumber_);
    }
    if (originOrderId_ != 0L) {
      output.writeInt64(6, originOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originOrderNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, originOrderNumber_);
    }
    if (type_ != com.yuanmai.protobuf.mall.aftersale.AfterSaleType.REFUND.getNumber()) {
      output.writeEnum(8, type_);
    }
    if (state_ != com.yuanmai.protobuf.mall.aftersale.AfterState.NONE.getNumber()) {
      output.writeEnum(9, state_);
    }
    if (temporaryState_ != com.yuanmai.protobuf.mall.order.OrderState.WAIT_APPROVED.getNumber()) {
      output.writeEnum(10, temporaryState_);
    }
    if (approvalState_ != com.yuanmai.protobuf.mall.approval.ApprovalStatus.NONE.getNumber()) {
      output.writeEnum(11, approvalState_);
    }
    if (amount_ != 0L) {
      output.writeInt64(12, amount_);
    }
    if (payAmount_ != 0L) {
      output.writeInt64(13, payAmount_);
    }
    if (reason_ != 0) {
      output.writeInt32(14, reason_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(remark_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, remark_);
    }
    if (operatorId_ != 0L) {
      output.writeInt64(17, operatorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, operator_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(19, items_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, address_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (supplierId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, supplierId_);
    }
    if (approvalId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, approvalId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, orderNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentOrderNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parentOrderNumber_);
    }
    if (originOrderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, originOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originOrderNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, originOrderNumber_);
    }
    if (type_ != com.yuanmai.protobuf.mall.aftersale.AfterSaleType.REFUND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, type_);
    }
    if (state_ != com.yuanmai.protobuf.mall.aftersale.AfterState.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, state_);
    }
    if (temporaryState_ != com.yuanmai.protobuf.mall.order.OrderState.WAIT_APPROVED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, temporaryState_);
    }
    if (approvalState_ != com.yuanmai.protobuf.mall.approval.ApprovalStatus.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, approvalState_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, amount_);
    }
    if (payAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, payAmount_);
    }
    if (reason_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, reason_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(remark_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, remark_);
    }
    if (operatorId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(17, operatorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, operator_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, items_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, address_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo)) {
      return super.equals(obj);
    }
    com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo other = (com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo) obj;

    if (getId()
        != other.getId()) return false;
    if (getSupplierId()
        != other.getSupplierId()) return false;
    if (getApprovalId()
        != other.getApprovalId()) return false;
    if (!getOrderNumber()
        .equals(other.getOrderNumber())) return false;
    if (!getParentOrderNumber()
        .equals(other.getParentOrderNumber())) return false;
    if (getOriginOrderId()
        != other.getOriginOrderId()) return false;
    if (!getOriginOrderNumber()
        .equals(other.getOriginOrderNumber())) return false;
    if (type_ != other.type_) return false;
    if (state_ != other.state_) return false;
    if (temporaryState_ != other.temporaryState_) return false;
    if (approvalState_ != other.approvalState_) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (getPayAmount()
        != other.getPayAmount()) return false;
    if (getReason()
        != other.getReason()) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getRemark()
        .equals(other.getRemark())) return false;
    if (getOperatorId()
        != other.getOperatorId()) return false;
    if (!getOperator()
        .equals(other.getOperator())) return false;
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + SUPPLIERID_FIELD_NUMBER;
    hash = (53 * hash) + getSupplierId();
    hash = (37 * hash) + APPROVALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getApprovalId());
    hash = (37 * hash) + ORDERNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getOrderNumber().hashCode();
    hash = (37 * hash) + PARENTORDERNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getParentOrderNumber().hashCode();
    hash = (37 * hash) + ORIGINORDERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOriginOrderId());
    hash = (37 * hash) + ORIGINORDERNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getOriginOrderNumber().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + TEMPORARYSTATE_FIELD_NUMBER;
    hash = (53 * hash) + temporaryState_;
    hash = (37 * hash) + APPROVALSTATE_FIELD_NUMBER;
    hash = (53 * hash) + approvalState_;
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + PAYAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPayAmount());
    hash = (37 * hash) + REASON_FIELD_NUMBER;
    hash = (53 * hash) + getReason();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + REMARK_FIELD_NUMBER;
    hash = (53 * hash) + getRemark().hashCode();
    hash = (37 * hash) + OPERATORID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOperatorId());
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + getOperator().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mall.protobuf.aftersale.AfterSaleOrderInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mall.protobuf.aftersale.AfterSaleOrderInfo)
      com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yuanmai.protobuf.mall.aftersale.Types.internal_static_mall_protobuf_aftersale_AfterSaleOrderInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yuanmai.protobuf.mall.aftersale.Types.internal_static_mall_protobuf_aftersale_AfterSaleOrderInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.class, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.Builder.class);
    }

    // Construct using com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      supplierId_ = 0;
      approvalId_ = 0L;
      orderNumber_ = "";
      parentOrderNumber_ = "";
      originOrderId_ = 0L;
      originOrderNumber_ = "";
      type_ = 0;
      state_ = 0;
      temporaryState_ = 0;
      approvalState_ = 0;
      amount_ = 0L;
      payAmount_ = 0L;
      reason_ = 0;
      description_ = "";
      remark_ = "";
      operatorId_ = 0L;
      operator_ = "";
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00040000);
      address_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yuanmai.protobuf.mall.aftersale.Types.internal_static_mall_protobuf_aftersale_AfterSaleOrderInfo_descriptor;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo getDefaultInstanceForType() {
      return com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo build() {
      com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo buildPartial() {
      com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo result = new com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00040000) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00040000);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.supplierId_ = supplierId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.approvalId_ = approvalId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.orderNumber_ = orderNumber_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.parentOrderNumber_ = parentOrderNumber_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.originOrderId_ = originOrderId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.originOrderNumber_ = originOrderNumber_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.temporaryState_ = temporaryState_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.approvalState_ = approvalState_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.payAmount_ = payAmount_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.reason_ = reason_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.remark_ = remark_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.operatorId_ = operatorId_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.operator_ = operator_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.address_ = address_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo) {
        return mergeFrom((com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo other) {
      if (other == com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getSupplierId() != 0) {
        setSupplierId(other.getSupplierId());
      }
      if (other.getApprovalId() != 0L) {
        setApprovalId(other.getApprovalId());
      }
      if (!other.getOrderNumber().isEmpty()) {
        orderNumber_ = other.orderNumber_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getParentOrderNumber().isEmpty()) {
        parentOrderNumber_ = other.parentOrderNumber_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getOriginOrderId() != 0L) {
        setOriginOrderId(other.getOriginOrderId());
      }
      if (!other.getOriginOrderNumber().isEmpty()) {
        originOrderNumber_ = other.originOrderNumber_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.temporaryState_ != 0) {
        setTemporaryStateValue(other.getTemporaryStateValue());
      }
      if (other.approvalState_ != 0) {
        setApprovalStateValue(other.getApprovalStateValue());
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (other.getPayAmount() != 0L) {
        setPayAmount(other.getPayAmount());
      }
      if (other.getReason() != 0) {
        setReason(other.getReason());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (!other.getRemark().isEmpty()) {
        remark_ = other.remark_;
        bitField0_ |= 0x00008000;
        onChanged();
      }
      if (other.getOperatorId() != 0L) {
        setOperatorId(other.getOperatorId());
      }
      if (!other.getOperator().isEmpty()) {
        operator_ = other.operator_;
        bitField0_ |= 0x00020000;
        onChanged();
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00040000);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00040000);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        bitField0_ |= 0x00080000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              supplierId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              approvalId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              orderNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              parentOrderNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              originOrderId_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              originOrderNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              temporaryState_ = input.readEnum();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              approvalState_ = input.readEnum();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              amount_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              payAmount_ = input.readInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              reason_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 130: {
              remark_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00008000;
              break;
            } // case 130
            case 136: {
              operatorId_ = input.readInt64();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            case 146: {
              operator_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00020000;
              break;
            } // case 146
            case 154: {
              com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem m =
                  input.readMessage(
                      com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 154
            case 162: {
              address_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00080000;
              break;
            } // case 162
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int supplierId_ ;
    /**
     * <pre>
     * 供货商ID
     * </pre>
     *
     * <code>int32 supplierId = 2;</code>
     * @return The supplierId.
     */
    @java.lang.Override
    public int getSupplierId() {
      return supplierId_;
    }
    /**
     * <pre>
     * 供货商ID
     * </pre>
     *
     * <code>int32 supplierId = 2;</code>
     * @param value The supplierId to set.
     * @return This builder for chaining.
     */
    public Builder setSupplierId(int value) {

      supplierId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 供货商ID
     * </pre>
     *
     * <code>int32 supplierId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSupplierId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      supplierId_ = 0;
      onChanged();
      return this;
    }

    private long approvalId_ ;
    /**
     * <pre>
     * 审核ID
     * </pre>
     *
     * <code>int64 approvalId = 3;</code>
     * @return The approvalId.
     */
    @java.lang.Override
    public long getApprovalId() {
      return approvalId_;
    }
    /**
     * <pre>
     * 审核ID
     * </pre>
     *
     * <code>int64 approvalId = 3;</code>
     * @param value The approvalId to set.
     * @return This builder for chaining.
     */
    public Builder setApprovalId(long value) {

      approvalId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审核ID
     * </pre>
     *
     * <code>int64 approvalId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearApprovalId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      approvalId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object orderNumber_ = "";
    /**
     * <pre>
     * 售后订单编号
     * </pre>
     *
     * <code>string orderNumber = 4;</code>
     * @return The orderNumber.
     */
    public java.lang.String getOrderNumber() {
      java.lang.Object ref = orderNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 售后订单编号
     * </pre>
     *
     * <code>string orderNumber = 4;</code>
     * @return The bytes for orderNumber.
     */
    public com.google.protobuf.ByteString
        getOrderNumberBytes() {
      java.lang.Object ref = orderNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 售后订单编号
     * </pre>
     *
     * <code>string orderNumber = 4;</code>
     * @param value The orderNumber to set.
     * @return This builder for chaining.
     */
    public Builder setOrderNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orderNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 售后订单编号
     * </pre>
     *
     * <code>string orderNumber = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderNumber() {
      orderNumber_ = getDefaultInstance().getOrderNumber();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 售后订单编号
     * </pre>
     *
     * <code>string orderNumber = 4;</code>
     * @param value The bytes for orderNumber to set.
     * @return This builder for chaining.
     */
    public Builder setOrderNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object parentOrderNumber_ = "";
    /**
     * <pre>
     * 父售后订单那编号
     * </pre>
     *
     * <code>string parentOrderNumber = 5;</code>
     * @return The parentOrderNumber.
     */
    public java.lang.String getParentOrderNumber() {
      java.lang.Object ref = parentOrderNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentOrderNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 父售后订单那编号
     * </pre>
     *
     * <code>string parentOrderNumber = 5;</code>
     * @return The bytes for parentOrderNumber.
     */
    public com.google.protobuf.ByteString
        getParentOrderNumberBytes() {
      java.lang.Object ref = parentOrderNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentOrderNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 父售后订单那编号
     * </pre>
     *
     * <code>string parentOrderNumber = 5;</code>
     * @param value The parentOrderNumber to set.
     * @return This builder for chaining.
     */
    public Builder setParentOrderNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentOrderNumber_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 父售后订单那编号
     * </pre>
     *
     * <code>string parentOrderNumber = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentOrderNumber() {
      parentOrderNumber_ = getDefaultInstance().getParentOrderNumber();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 父售后订单那编号
     * </pre>
     *
     * <code>string parentOrderNumber = 5;</code>
     * @param value The bytes for parentOrderNumber to set.
     * @return This builder for chaining.
     */
    public Builder setParentOrderNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentOrderNumber_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long originOrderId_ ;
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>int64 originOrderId = 6;</code>
     * @return The originOrderId.
     */
    @java.lang.Override
    public long getOriginOrderId() {
      return originOrderId_;
    }
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>int64 originOrderId = 6;</code>
     * @param value The originOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginOrderId(long value) {

      originOrderId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>int64 originOrderId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginOrderId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      originOrderId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object originOrderNumber_ = "";
    /**
     * <pre>
     * 订单编号
     * </pre>
     *
     * <code>string originOrderNumber = 7;</code>
     * @return The originOrderNumber.
     */
    public java.lang.String getOriginOrderNumber() {
      java.lang.Object ref = originOrderNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originOrderNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 订单编号
     * </pre>
     *
     * <code>string originOrderNumber = 7;</code>
     * @return The bytes for originOrderNumber.
     */
    public com.google.protobuf.ByteString
        getOriginOrderNumberBytes() {
      java.lang.Object ref = originOrderNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originOrderNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 订单编号
     * </pre>
     *
     * <code>string originOrderNumber = 7;</code>
     * @param value The originOrderNumber to set.
     * @return This builder for chaining.
     */
    public Builder setOriginOrderNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originOrderNumber_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订单编号
     * </pre>
     *
     * <code>string originOrderNumber = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginOrderNumber() {
      originOrderNumber_ = getDefaultInstance().getOriginOrderNumber();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订单编号
     * </pre>
     *
     * <code>string originOrderNumber = 7;</code>
     * @param value The bytes for originOrderNumber to set.
     * @return This builder for chaining.
     */
    public Builder setOriginOrderNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originOrderNumber_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 退款类型 0=退款,1=退货退款,2=换货
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 退款类型 0=退款,1=退货退款,2=换货
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 退款类型 0=退款,1=退货退款,2=换货
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleType getType() {
      com.yuanmai.protobuf.mall.aftersale.AfterSaleType result = com.yuanmai.protobuf.mall.aftersale.AfterSaleType.forNumber(type_);
      return result == null ? com.yuanmai.protobuf.mall.aftersale.AfterSaleType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 退款类型 0=退款,1=退货退款,2=换货
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.yuanmai.protobuf.mall.aftersale.AfterSaleType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 退款类型 0=退款,1=退货退款,2=换货
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterSaleType type = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      type_ = 0;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <pre>
     * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.aftersale.AfterState getState() {
      com.yuanmai.protobuf.mall.aftersale.AfterState result = com.yuanmai.protobuf.mall.aftersale.AfterState.forNumber(state_);
      return result == null ? com.yuanmai.protobuf.mall.aftersale.AfterState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.yuanmai.protobuf.mall.aftersale.AfterState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0 未发起售后 1 申请售后 -1 售后已取消 2 处理中 3 处理完毕
     * </pre>
     *
     * <code>.mall.protobuf.aftersale.AfterState state = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000100);
      state_ = 0;
      onChanged();
      return this;
    }

    private int temporaryState_ = 0;
    /**
     * <pre>
     * 临时订单状态 记录提交售后时，订单状态
     * </pre>
     *
     * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
     * @return The enum numeric value on the wire for temporaryState.
     */
    @java.lang.Override public int getTemporaryStateValue() {
      return temporaryState_;
    }
    /**
     * <pre>
     * 临时订单状态 记录提交售后时，订单状态
     * </pre>
     *
     * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
     * @param value The enum numeric value on the wire for temporaryState to set.
     * @return This builder for chaining.
     */
    public Builder setTemporaryStateValue(int value) {
      temporaryState_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 临时订单状态 记录提交售后时，订单状态
     * </pre>
     *
     * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
     * @return The temporaryState.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.order.OrderState getTemporaryState() {
      com.yuanmai.protobuf.mall.order.OrderState result = com.yuanmai.protobuf.mall.order.OrderState.forNumber(temporaryState_);
      return result == null ? com.yuanmai.protobuf.mall.order.OrderState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 临时订单状态 记录提交售后时，订单状态
     * </pre>
     *
     * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
     * @param value The temporaryState to set.
     * @return This builder for chaining.
     */
    public Builder setTemporaryState(com.yuanmai.protobuf.mall.order.OrderState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000200;
      temporaryState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 临时订单状态 记录提交售后时，订单状态
     * </pre>
     *
     * <code>.mall.protobuf.order.OrderState temporaryState = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemporaryState() {
      bitField0_ = (bitField0_ & ~0x00000200);
      temporaryState_ = 0;
      onChanged();
      return this;
    }

    private int approvalState_ = 0;
    /**
     * <pre>
     * 审核状态
     * </pre>
     *
     * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
     * @return The enum numeric value on the wire for approvalState.
     */
    @java.lang.Override public int getApprovalStateValue() {
      return approvalState_;
    }
    /**
     * <pre>
     * 审核状态
     * </pre>
     *
     * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
     * @param value The enum numeric value on the wire for approvalState to set.
     * @return This builder for chaining.
     */
    public Builder setApprovalStateValue(int value) {
      approvalState_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审核状态
     * </pre>
     *
     * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
     * @return The approvalState.
     */
    @java.lang.Override
    public com.yuanmai.protobuf.mall.approval.ApprovalStatus getApprovalState() {
      com.yuanmai.protobuf.mall.approval.ApprovalStatus result = com.yuanmai.protobuf.mall.approval.ApprovalStatus.forNumber(approvalState_);
      return result == null ? com.yuanmai.protobuf.mall.approval.ApprovalStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 审核状态
     * </pre>
     *
     * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
     * @param value The approvalState to set.
     * @return This builder for chaining.
     */
    public Builder setApprovalState(com.yuanmai.protobuf.mall.approval.ApprovalStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000400;
      approvalState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 审核状态
     * </pre>
     *
     * <code>.mall.protobuf.approval.ApprovalStatus approvalState = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearApprovalState() {
      bitField0_ = (bitField0_ & ~0x00000400);
      approvalState_ = 0;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <pre>
     * 总金额
     * </pre>
     *
     * <code>int64 amount = 12;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * 总金额
     * </pre>
     *
     * <code>int64 amount = 12;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {

      amount_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总金额
     * </pre>
     *
     * <code>int64 amount = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000800);
      amount_ = 0L;
      onChanged();
      return this;
    }

    private long payAmount_ ;
    /**
     * <pre>
     * 实际支付金额
     * </pre>
     *
     * <code>int64 payAmount = 13;</code>
     * @return The payAmount.
     */
    @java.lang.Override
    public long getPayAmount() {
      return payAmount_;
    }
    /**
     * <pre>
     * 实际支付金额
     * </pre>
     *
     * <code>int64 payAmount = 13;</code>
     * @param value The payAmount to set.
     * @return This builder for chaining.
     */
    public Builder setPayAmount(long value) {

      payAmount_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际支付金额
     * </pre>
     *
     * <code>int64 payAmount = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayAmount() {
      bitField0_ = (bitField0_ & ~0x00001000);
      payAmount_ = 0L;
      onChanged();
      return this;
    }

    private int reason_ ;
    /**
     * <pre>
     * 客户 选择原因
     * </pre>
     *
     * <code>int32 reason = 14;</code>
     * @return The reason.
     */
    @java.lang.Override
    public int getReason() {
      return reason_;
    }
    /**
     * <pre>
     * 客户 选择原因
     * </pre>
     *
     * <code>int32 reason = 14;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(int value) {

      reason_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户 选择原因
     * </pre>
     *
     * <code>int32 reason = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      bitField0_ = (bitField0_ & ~0x00002000);
      reason_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 15;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 15;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 15;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string description = 15;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private java.lang.Object remark_ = "";
    /**
     * <pre>
     * 备注 客服填写
     * </pre>
     *
     * <code>string remark = 16;</code>
     * @return The remark.
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 备注 客服填写
     * </pre>
     *
     * <code>string remark = 16;</code>
     * @return The bytes for remark.
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 备注 客服填写
     * </pre>
     *
     * <code>string remark = 16;</code>
     * @param value The remark to set.
     * @return This builder for chaining.
     */
    public Builder setRemark(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      remark_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 备注 客服填写
     * </pre>
     *
     * <code>string remark = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemark() {
      remark_ = getDefaultInstance().getRemark();
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 备注 客服填写
     * </pre>
     *
     * <code>string remark = 16;</code>
     * @param value The bytes for remark to set.
     * @return This builder for chaining.
     */
    public Builder setRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      remark_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }

    private long operatorId_ ;
    /**
     * <pre>
     * 操作人
     * </pre>
     *
     * <code>int64 operatorId = 17;</code>
     * @return The operatorId.
     */
    @java.lang.Override
    public long getOperatorId() {
      return operatorId_;
    }
    /**
     * <pre>
     * 操作人
     * </pre>
     *
     * <code>int64 operatorId = 17;</code>
     * @param value The operatorId to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorId(long value) {

      operatorId_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作人
     * </pre>
     *
     * <code>int64 operatorId = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatorId() {
      bitField0_ = (bitField0_ & ~0x00010000);
      operatorId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object operator_ = "";
    /**
     * <pre>
     * 操作人姓名
     * </pre>
     *
     * <code>string operator = 18;</code>
     * @return The operator.
     */
    public java.lang.String getOperator() {
      java.lang.Object ref = operator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 操作人姓名
     * </pre>
     *
     * <code>string operator = 18;</code>
     * @return The bytes for operator.
     */
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      java.lang.Object ref = operator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 操作人姓名
     * </pre>
     *
     * <code>string operator = 18;</code>
     * @param value The operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperator(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      operator_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作人姓名
     * </pre>
     *
     * <code>string operator = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperator() {
      operator_ = getDefaultInstance().getOperator();
      bitField0_ = (bitField0_ & ~0x00020000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作人姓名
     * </pre>
     *
     * <code>string operator = 18;</code>
     * @param value The bytes for operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operator_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }

    private java.util.List<com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00040000) != 0)) {
        items_ = new java.util.ArrayList<com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem>(items_);
        bitField0_ |= 0x00040000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder setItems(
        int index, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder setItems(
        int index, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder addItems(com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder addItems(
        int index, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder addItems(
        com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder addItems(
        int index, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00040000);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public java.util.List<? extends com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 售后商品
     * </pre>
     *
     * <code>repeated .mall.protobuf.aftersale.AfterSaleOrderItem items = 19;</code>
     */
    public java.util.List<com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItem.Builder, com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00040000) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 20;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 20;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 20;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      address_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      address_ = getDefaultInstance().getAddress();
      bitField0_ = (bitField0_ & ~0x00080000);
      onChanged();
      return this;
    }
    /**
     * <code>string address = 20;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      address_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mall.protobuf.aftersale.AfterSaleOrderInfo)
  }

  // @@protoc_insertion_point(class_scope:mall.protobuf.aftersale.AfterSaleOrderInfo)
  private static final com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo();
  }

  public static com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AfterSaleOrderInfo>
      PARSER = new com.google.protobuf.AbstractParser<AfterSaleOrderInfo>() {
    @java.lang.Override
    public AfterSaleOrderInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AfterSaleOrderInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AfterSaleOrderInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yuanmai.protobuf.mall.aftersale.AfterSaleOrderInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

