name: Publish to Nexus

on:
  push:
    branches:
      - master
env:
  groupId: com.yuanmai.protobuf
  artifactId: yuanmai-mall-java

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Build and Deploy with Maven
        run: mvn deploy -Dpassword=${{ secrets.password }} --file pom.xml -s settings.xml
